'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {pathToFileURL}=require('node:url');
const protocolPromise=import(pathToFileURL(path.resolve(__dirname,'../../shared/reports/protocol.mjs')));
const EXPECTED=new Set(['VALIDATION','INVALID_INPUT','FORBIDDEN','UNAUTHENTICATED','SESSION_CHANGED','UI_STALE','CANCELED','CANCELLED','LICENSE_REQUIRED','LICENSE_EXPIRED','CAPABILITY_UNAVAILABLE','PLATFORM_UNAVAILABLE']);
const FAILURE=new Set(['failed','partial','unknown','accepted','rejected','needs_attention','timeout']);
function outcome(result){
 const queue=[result];let inspected=0;
 while(queue.length&&inspected++<64){const r=queue.shift();if(!r||typeof r!=='object')continue;if(r.ok===false||FAILURE.has(r.status))return {status:r.status||'failed',code:r.code||r.error?.code};for(const field of ['results','errors','items'])if(Array.isArray(r[field]))queue.push(...r[field].slice(0,32));}
 return {status:result?.status||'ok',code:result?.code};
}
function fail(code,message){throw Object.assign(new Error(message),{code});}
function atom(file,data){fs.mkdirSync(path.dirname(file),{recursive:true});const temp=file+'.tmp';fs.writeFileSync(temp,data);fs.renameSync(temp,file);}
class Reports {
 constructor({directory,protector,version,build='development',fetchImpl=globalThis.fetch,endpoint='',getLicense=()=>null,clock=Date.now}){Object.assign(this,{directory,protector,version,build,fetchImpl,endpoint,getLicense,clock});this.ready=false;this.logs=[];this.records=new Map();this.attachments=new Map();this.busy=false;this.ticket=null;this.timer=null;this.flushTimer=null;this.blockedUntil=0;this.health='not_connected';this.lastCode=null;}
 async init(){this.p=await protocolPromise;fs.mkdirSync(this.directory,{recursive:true});if(!this.protector?.isEncryptionAvailable()) {this.lastCode='REPORT_STORAGE_UNAVAILABLE';return;}
  const settingsFile=path.join(this.directory,'settings.bin');
  try{this.settings=fs.existsSync(settingsFile)?this.read(settingsFile):{v:1,automatic:null,noticed:false,installId:crypto.randomUUID(),keys:crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1',publicKeyEncoding:{type:'spki',format:'der'},privateKeyEncoding:{type:'pkcs8',format:'pem'}})};if(Buffer.isBuffer(this.settings.keys.publicKey))this.settings.keys.publicKey=this.settings.keys.publicKey.toString('base64url');if(!this.settings.installId||!this.settings.keys?.privateKey)throw Error('bad');this.write(settingsFile,this.settings);
   for(const file of fs.readdirSync(this.directory).filter(x=>/^[a-f0-9-]{36}\.report$/.test(x))){try{const r=this.read(path.join(this.directory,file));this.p.normalizeReport(r.report);if(r.report.id+'.report'!==file)continue;this.records.set(r.report.id,r);}catch{this.lastCode='REPORT_RECORD_DAMAGED';}}
   this.ready=true;this.pruneLogs();const sessionFile=path.join(this.directory,'session.bin');const prior=fs.existsSync(sessionFile)?this.read(sessionFile):null;this.write(sessionFile,{clean:false,at:this.clock()});if(prior&&!prior.clean)this.capture('app.previousExit',null,{code:'PREVIOUS_EXIT_UNCLEAN',status:'unknown'}, {id:'system',role:'owner'},{source:'system'});
  }catch{this.lastCode='REPORT_STORAGE_UNAVAILABLE';this.ready=false;}
 }
 read(file){return JSON.parse(this.protector.decryptString(fs.readFileSync(file)));}
 write(file,value){atom(file,this.protector.encryptString(JSON.stringify(value)));}
 persist(r){this.write(path.join(this.directory,r.report.id+'.report'),r);this.records.set(r.report.id,r);}
 activate(active){if(this.ready&&active&&this.settings.automatic===null){this.settings.automatic=true;this.write(path.join(this.directory,'settings.bin'),this.settings);}}
 status(actor){return {ready:this.ready,automatic:this.settings?.automatic===true,noticeRequired:this.settings?.automatic===true&&!this.settings?.noticed,canConfigure:actor?.role==='owner',connection:this.health,code:this.lastCode,queued:this.list(actor).filter(r=>r.state==='queued').length,privacy:'自动报告不包含聊天正文、买家身份、凭据和资料内容；截图仅主动选择后发送。'};}
 configure(input,actor){if(actor?.role!=='owner')fail('FORBIDDEN','仅本机管理员可以调整自动回传。');if(!this.ready)fail('REPORT_STORAGE_UNAVAILABLE','本机诊断存储未就绪。');if(typeof input.automatic==='boolean')this.settings.automatic=input.automatic;if(input.noticed===true)this.settings.noticed=true;this.write(path.join(this.directory,'settings.bin'),this.settings);return this.status(actor);}
 allowed(r,actor){return actor?.role==='owner'||r.owner===(actor?.id||'guest');}
 list(actor){return [...this.records.values()].filter(r=>this.allowed(r,actor)).map(r=>({id:r.report.id,kind:r.report.kind,at:r.report.at,feature:r.report.feature,state:r.state,github:r.github||null,code:r.code||null,attachments:r.report.attachments.length,uploaded:r.uploaded?.length||0,description:r.report.description||'',count:r.report.count})).sort((a,b)=>b.at-a.at);}
 get(id,actor){const r=this.records.get(id);if(!r||!this.allowed(r,actor))fail('FORBIDDEN','无法读取此反馈。');return r;}
 pruneLogs(){const files=fs.readdirSync(this.directory).filter(x=>/^log-\d+\.bin$/.test(x)).sort();let size=files.reduce((s,f)=>s+fs.statSync(path.join(this.directory,f)).size,0);for(const f of files){const full=path.join(this.directory,f),stat=fs.statSync(full);if(size>20*1024*1024||stat.mtimeMs<this.clock()-7*86400000){fs.unlinkSync(full);size-=stat.size;}}}
 flushLogs(){if(!this.ready||!this.buffer?.length)return;try{this.write(path.join(this.directory,'log-'+this.clock()+'.bin'),this.buffer.splice(0));this.pruneLogs();}catch{this.lastCode='REPORT_STORAGE_WRITE';}}
 capture(feature,error,result,actor={},ctx={}){try{if(!this.ready||/^(feedback\.|diagnostics\.|app.activity|app.editState)/.test(feature))return;result=outcome(result);const p=this.p,at=this.clock(),code=p.tag(error?.code||result?.code,error?'UNEXPECTED_EXCEPTION':'OPERATION_RESULT');const info={feature:p.tag(feature),at,...p.context(ctx),result:p.tag(error?'failed':result?.status||'ok')};this.logs.push({...info,owner:actor.id||'guest'});this.logs=this.logs.slice(-300);(this.buffer||=[]).push({...info,owner:crypto.createHash('sha256').update(actor.id||'guest').digest('hex').slice(0,16)});if(!this.flushTimer)this.flushTimer=setTimeout(()=>{this.flushTimer=null;this.flushLogs();},500).unref();
   if(!this.settings.automatic||EXPECTED.has(code)||(!error&&!FAILURE.has(result?.status)))return;
   const frames=p.frameList(error?.stack),fingerprint=crypto.createHash('sha256').update(JSON.stringify([this.version,feature,code,frames,actor.id||'guest'])).digest('hex');
   const same=[...this.records.values()].find(r=>r.fingerprint===fingerprint&&r.report.at>at-86400000);
   if(same){if(same.state==='queued'&&!same.attempted){same.report.count++;same.report.at=at;this.persist(same);}return;}
   if([...this.records.values()].filter(r=>r.report.kind==='automatic'&&r.report.at>at-86400000).length>=20)return;
   const report=p.normalizeReport({id:crypto.randomUUID(),kind:'automatic',version:this.version,build:this.build,platform:'Windows-'+require('node:os').release()+'-'+process.arch,feature,code,at,context:ctx,frames,steps:this.logs.filter(x=>x.owner===(actor.id||'guest')).slice(-30)});
   this.capacity();this.persist({owner:actor.id||'guest',report,state:'queued',fingerprint,uploaded:[]});
  }catch{this.lastCode='REPORT_RECORD_FAILED';}}
 capacity(extra=0){if(this.records.size>=100||fs.readdirSync(this.directory).reduce((s,f)=>s+fs.statSync(path.join(this.directory,f)).size,extra)>50*1024*1024)fail('REPORT_LOCAL_FULL','本地反馈空间已满，请导出或清理已提交记录。');}
 preview(input,actor){if(!this.ready)fail('REPORT_STORAGE_UNAVAILABLE','诊断存储尚未就绪，请保留当前错误提示。');const attachments=(input.attachmentIds||[]).map(id=>{const a=this.attachments.get(id);if(!a||a.owner!==(actor?.id||'guest'))fail('FORBIDDEN','截图不属于当前成员，请重新选择。');return a.meta;});return this.p.normalizeReport({...input,id:input.id||crypto.randomUUID(),kind:'manual',version:this.version,build:this.build,platform:'Windows-'+require('node:os').release()+'-'+process.arch,feature:this.p.tag(input.feature,'feedback.manual'),code:'USER_FEEDBACK',at:this.clock(),steps:this.logs.filter(x=>x.owner===(actor?.id||'guest')).slice(-30),context:{role:actor?.role||'guest',source:'manual'},attachments});}
 draft(input,actor){const report=this.preview(input,actor);const existing=this.records.get(report.id);if(existing){this.get(report.id,actor);if(existing.state!=='draft')fail('REPORT_IMMUTABLE','已提交的反馈不能修改，请新建补充反馈。');}else this.capacity();const r={owner:actor?.id||'guest',report,state:'draft',uploaded:[]};for(const meta of report.attachments){const a=this.attachments.get(meta.id);this.write(path.join(this.directory,meta.id+'.image'),{owner:r.owner,reportId:report.id,mime:meta.mime,data:a.bytes.toString('base64')});}this.persist(r);return {id:report.id,state:r.state,report};}
 addImage(bytes,mime,actor){this.capacity(bytes.length);if(bytes.length>262144)fail('REPORT_IMAGE_LARGE','每张截图处理后不能超过 256 KiB。');const id=crypto.randomUUID(),meta={id,size:bytes.length,mime,digest:crypto.createHash('sha256').update(bytes).digest('base64url')};this.attachments.set(id,{owner:actor?.id||'guest',meta,bytes});if(this.attachments.size>10)this.attachments.delete(this.attachments.keys().next().value);return meta;}
 async submit(input,actor){let r;if(input.id&&this.records.has(input.id)){r=this.get(input.id,actor);if(r.state==='draft'&&input.description)r=this.records.get(this.draft(input,actor).id);}else r=this.records.get(this.draft(input,actor).id);r.state='queued';this.persist(r);await this.send(r);return this.list(actor).find(x=>x.id===r.report.id);}
 async post(route,body){if(!/^https:\/\//.test(this.endpoint))fail('REPORT_NOT_CONFIGURED','回传服务尚未接通。');const response=await this.fetchImpl(this.endpoint+route,{method:'POST',redirect:'error',credentials:'omit',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});let n=0,chunks=[];const reader=response.body?.getReader();if(!reader)fail('REPORT_NETWORK','没有收到有效回执。');while(true){const part=await reader.read();if(part.done)break;n+=part.value.length;if(n>65536){await reader.cancel();fail('REPORT_RESPONSE','回执超过限制。');}chunks.push(Buffer.from(part.value));}let envelope;try{envelope=JSON.parse(Buffer.concat(chunks));}catch{fail('REPORT_NETWORK','尚未收到完整回执。');}if(!response.ok||!envelope.ok)fail(this.p.tag(envelope.error?.code,'REPORT_NETWORK'),'回传暂未完成，请保留原报告。');return envelope.data;}
 async session(){if(this.ticket?.expiresAt>this.clock()+60000)return this.ticket;const p=this.p,nonce=crypto.randomUUID(),publicKey=this.settings.keys.publicKey;const fresh=await this.post('/v1/reports/challenge',{publicKey,nonce});const challenge=fresh.challenge;if(typeof challenge!=='string'||fresh.expiresAt<=this.clock())fail('REPORT_AUTH','反馈核验票据已过期。');let proof=null;try{proof=await this.getLicense(p.proofBytes('session',{publicKey,nonce,challenge}));}catch{}
  const request={v:1,publicKey,nonce,challenge,...(proof?{license:proof.license,devicePublicKey:proof.publicKey,proof:proof.signature}:{})};const result=await this.post('/v1/reports/session',request);if(typeof result.token!=='string'||!Number.isSafeInteger(result.expiresAt))fail('REPORT_RESPONSE','反馈凭据未通过核验。');this.ticket=result;return result;}
 async request(route,body){const ticket=await this.session();if(route==='submit'&&body.report.kind==='automatic'&&!this.settings.automatic)fail('REPORT_DISABLED','自动回传已关闭。');const signature=crypto.sign('sha256',this.p.proofBytes(route,{token:ticket.token,body}),{key:this.settings.keys.privateKey,dsaEncoding:'ieee-p1363'}).toString('base64url');return this.post('/v1/reports/'+route,{v:1,token:ticket.token,body,signature});}
 async send(r){if(this.busy||this.clock()<this.blockedUntil)return;this.busy=true;try{r.attempted=true;this.persist(r);const ack=await this.request('submit',{report:r.report});if(ack.id!==r.report.id||ack.received!==true)fail('REPORT_RESPONSE','尚未确认云端收件。');r.state='received';r.github=ack.github;r.code=null;this.health='connected';this.persist(r);
  for(const meta of r.report.attachments){if(r.uploaded.includes(meta.id))continue;const a=this.read(path.join(this.directory,meta.id+'.image'));if(a.owner!==r.owner||a.reportId!==r.report.id)fail('REPORT_IMAGE_OWNER','截图归属不一致。');const image=await this.request('attachment',{id:r.report.id,attachmentId:meta.id,data:a.data});if(image.saved!==true)fail('REPORT_RESPONSE','截图尚未确认。');r.uploaded.push(meta.id);this.persist(r);}
 }catch(error){r.code=this.p.tag(error.code,'REPORT_NETWORK');this.lastCode=r.code;this.health=r.code==='REPORT_NOT_CONFIGURED'||r.code==='NOT_FOUND'?'not_connected':'unavailable';if(r.state==='received'&&r.uploaded.length<r.report.attachments.length)r.state='attachments_pending';try{this.persist(r);}catch{}this.ticket=null;this.blockedUntil=this.clock()+(/QUOTA|FULL/.test(r.code)?86400000:60000);}finally{this.busy=false;}}
 async refresh(id,actor){const r=this.get(id,actor);try{const data=await this.request('status',{id});if(data.id!==id)fail('REPORT_RESPONSE','回执不匹配。');r.github=data.github;r.code=null;this.persist(r);}catch(error){r.code=this.p.tag(error.code,'REPORT_NETWORK');this.persist(r);}return this.list(actor).find(x=>x.id===id);}
 start(){this.timer=setInterval(()=>{const r=[...this.records.values()].find(x=>(x.state==='queued'||x.state==='attachments_pending')&&(x.report.kind==='manual'||this.settings?.automatic));if(r)void this.send(r);},60000).unref();}
 close(){clearInterval(this.timer);clearTimeout(this.flushTimer);this.flushLogs();if(this.ready)try{this.write(path.join(this.directory,'session.bin'),{clean:true,at:this.clock()});}catch{}}
}
module.exports={Reports,EXPECTED};
