'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {randomBytes}=require('node:crypto');
const {EncryptedStore}=require('../src/core/store.cjs');const {Service}=require('../src/core/service.cjs');
const owner={id:'owner',role:'owner',accountIds:[]};
async function setup(t,connector={}){const store=new EncryptedStore(':memory:',randomBytes(32));const service=new Service(store,{connector});const run=(a,p)=>service.run(a,p,owner);t.after(()=>store.close());await run('test.seed');store.put('messages',{...store.get('messages','test-message-1'),receivedAt:new Date(Date.now()-10000).toISOString()});const conversation=store.get('conversations','test-conversation-1');const prefs=async patch=>run('entity.save',{kind:'settings',record:{...store.get('settings','test-preferences'),...patch}});const incoming=(id,text)=>store.put('messages',{id,space:'test',accountId:conversation.accountId,conversationId:conversation.id,buyerId:conversation.buyerId,text,direction:'incoming',origin:'test',status:'received',receivedAt:new Date(Date.now()+1).toISOString(),createdAt:new Date().toISOString()});return {store,service,run,conversation,prefs,incoming};}
test('F37/F38 默认回复严格在规则与AI之后，默认每会话一次',async t=>{
  t.diagnostic('假设：固定规则优先，AI次之，无可用答案才默认兜底且限一次；决策价值：防止UI默认设置为空操作或抢占AI；停止条件：四种不同顺序分支各一次。');
  let aiCalls=0,response={text:'AI批准的公开答复',constrained:true};const f=await setup(t,{testOnly:true,sendMessage:async()=>({status:'sent'}),aiReply:async()=>{aiCalls++;return response;}});await f.prefs({autoEnabled:true,aiEnabled:true,defaultReply:'商家设置的默认答复'});
  f.incoming('first','随机问题');let tick=await f.run('automation.tick',{space:'test'});assert.equal(tick.replies.length,1);assert.equal(tick.replies[0].text,'AI批准的公开答复');assert.equal(aiCalls,1);
  response={text:'',constrained:true,handoff:true};f.incoming('second','不确定问题');tick=await f.run('automation.tick',{space:'test'});assert.equal(tick.replies.length,1);assert.equal(tick.replies[0].text,'商家设置的默认答复');
  f.incoming('third','仍不确定');tick=await f.run('automation.tick',{space:'test'});assert.equal(tick.replies.length,0);
  await f.run('entity.save',{kind:'replyRules',record:{id:'keyword',space:'test',accountId:f.conversation.accountId,name:'关键词',keywords:['关键词'],text:'固定规则答复',enabled:true}});const before=aiCalls;f.incoming('fourth','关键词问题');tick=await f.run('automation.tick',{space:'test'});assert.equal(tick.replies[0].text,'固定规则答复');assert.equal(aiCalls,before);assert.equal(f.store.get('_automation','third').status,'needs_attention');
});
test('F37/F39 全局排除阻断AI和默认，客户策略只影响同账号买家',async t=>{
  t.diagnostic('假设：被排除商品不走任何自动答复，客户标记不会串账号；决策价值：决定设置和客户管理实际可用；停止条件：全局排除、客户屏蔽、置顶接待范围各一次。');
  let aiCalls=0;const f=await setup(t,{aiReply:async()=>{aiCalls++;return {text:'不应生成',constrained:true};}});await f.prefs({autoEnabled:true,aiEnabled:true,defaultReply:'默认回复',excludedProductIds:['test-product-1']});await f.run('entity.save',{kind:'replyRules',record:{...f.store.get('replyRules','test-reply-rule-1'),enabled:true}});
  assert.equal((await f.run('reply.preview',{conversationId:f.conversation.id,text:'领取'})).eligible,false);assert.equal((await f.run('ai.preview',{conversationId:f.conversation.id,text:'领取'})).eligible,false);assert.equal(aiCalls,0);f.incoming('excluded','领取');assert.equal((await f.run('automation.tick',{space:'test'})).replies.length,0);assert.equal(aiCalls,0);assert.equal((await f.run('message.preview',{conversationId:f.conversation.id,text:'人工确认内容'})).eligible,true);
  await f.prefs({excludedProductIds:[]});f.store.put('members',{id:'owner',role:'owner',enabled:true,accountIds:[]});f.store.put('members',{id:'operator',name:'接待人',role:'operator',enabled:true,accountIds:[f.conversation.accountId]});
  await f.run('entity.save',{kind:'customers',record:{id:'customer',space:'test',accountId:f.conversation.accountId,buyerId:f.conversation.buyerId,name:'客户',blocked:true,pinned:true,assigneeId:'operator'}});assert.equal((await f.run('reply.preview',{conversationId:f.conversation.id,text:'领取'})).eligible,false);assert.equal((await f.run('ai.preview',{conversationId:f.conversation.id,text:'领取'})).eligible,false);assert.equal(f.store.get('conversations',f.conversation.id).pinned,true);assert.equal(f.store.get('conversations',f.conversation.id).assigneeId,'operator');
  await f.run('entity.save',{kind:'accounts',record:{id:'other-account',space:'test',name:'另一个账号'}});const other=await f.run('entity.save',{kind:'conversations',record:{id:'other-conversation',space:'test',accountId:'other-account',buyerId:f.conversation.buyerId,manual:false}});assert.equal((await f.run('reply.preview',{conversationId:other.id,text:'另一个会话'})).eligible,true);assert.equal(f.store.get('conversations',other.id).pinned,undefined);assert.equal(f.store.get('conversations',other.id).assigneeId,undefined);
});
test('F30 随单致谢进入完整交付快照，收货后规则延后赠品致谢',async t=>{
  t.diagnostic('假设：配置的随单致谢真正出现在消息快照，收货后条件不能提前执行；决策价值：决定规则文案是否可启用；停止条件：随单文本和afterReceipt延后内容各一次。');
  const f=await setup(t);const rule=f.store.get('rules','test-rule-1');await f.run('entity.save',{kind:'rules',record:{...rule,enabled:true,thankYou:'感谢购买，有问题请联系人工。'}});let preview=await f.run('delivery.preview',{orderId:'test-order-1'});assert.equal(preview.eligible,true);assert.ok(preview.text.endsWith('感谢购买，有问题请联系人工。'));const sent=await f.run('delivery.execute',{orderId:'test-order-1'});assert.ok(f.store.get('deliveries',sent.id).text.endsWith('感谢购买，有问题请联系人工。'));
  await f.run('entity.save',{kind:'rules',record:{...f.store.get('rules',rule.id),afterReceipt:true}});preview=await f.run('delivery.preview',{orderId:'test-order-1'});assert.equal(preview.eligible,false);assert.equal(preview.afterReceiptDeferred,true);assert.ok(!preview.text.includes('感谢购买，有问题请联系人工。'));
});
