'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {Reports}=require('../src/services/reports.cjs');
const hypothesis={claim:'Support is recoverable, scoped and contains no automatic business content',decision:'Release only if privacy, persistence and deduplication checks pass',stop:'First incorrect disclosure or changed report after an uncertain submission'};
const owner={id:'owner',role:'owner'},other={id:'other',role:'support'};
const protector={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s).map(b=>b^93),decryptString:b=>Buffer.from(b).map(b=>b^93).toString()};
async function fixture(t,options={}){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'lianpu-reports-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const r=new Reports({directory,protector,version:'0.5.4',...options});await r.init();t.after(()=>r.close());return r;}
test('activation defaults once, opt-out and private drafts survive restart',async t=>{const r=await fixture(t);r.activate(true);assert.equal(r.status(owner).automatic,true);r.configure({automatic:false},owner);const d=r.draft({description:'按钮点击后没有响应',feature:'accounts.check'},other);assert.equal(r.list({id:'stranger',role:'viewer'}).length,0);assert.throws(()=>r.get(d.id,{id:'stranger'}));r.close();const second=new Reports({directory:r.directory,protector,version:'0.5.4'});await second.init();second.activate(true);assert.equal(second.status(owner).automatic,false);assert.equal(second.get(d.id,other).report.description,'按钮点击后没有响应');second.close();});
test('automatic reports only use whitelisted context and relative frames',async t=>{const r=await fixture(t);r.activate(true);const secret='LP1-P-'+'A'.repeat(40),e=Object.assign(new Error('Cookie: abc https://example.com/private '+secret),{code:'READ_FAILED'});e.stack='Error: Cookie secret\n at sync (C:\\Users\\Person Name\\app\\src\\platform\\xianyu.cjs:32:4)';r.capture('account.sync',e,null,owner,{source:'manual',cookie:'abc',buyerName:'PRIVATE_BUYER',link:'secret'});const rows=r.list(owner);assert.equal(rows.length,1);const report=r.get(rows[0].id,owner).report;assert.deepEqual(report.frames,['src/platform/xianyu.cjs:32:4']);const text=JSON.stringify(report);for(const s of ['abc',secret,'PRIVATE_BUYER','Person Name','example.com'])assert.equal(text.includes(s),false,s);r.capture('account.sync',e,null,owner,{});assert.equal(r.get(rows[0].id,owner).report.count,2);r.capture('entity.save',Object.assign(Error('required'),{code:'VALIDATION'}),null,owner);assert.equal(r.list(owner).length,1);});
test('same immutable report is retried after response loss; screenshot partial state persists',async t=>{const r=await fixture(t);const image=r.addImage(Buffer.from([255,216,1,2]),'image/jpeg',owner),d=r.draft({feature:'accounts.check',description:'无法展开',attachmentIds:[image.id]},owner);const attempts=[];let n=0;r.request=async(op,body)=>{attempts.push({op,body});if(op==='submit'){if(n++===0)throw Error('timeout');return {id:body.report.id,received:true,github:'pending'};}throw Error('image timeout');};await r.submit({id:d.id},owner);assert.equal(r.get(d.id,owner).state,'queued');r.blockedUntil=0;await r.submit({id:d.id},owner);assert.equal(r.get(d.id,owner).state,'attachments_pending');assert.deepEqual(attempts[0].body,attempts[1].body);assert.equal(r.get(d.id,owner).uploaded.length,0);});
test('no encryption means no plaintext fallback or false draft success',async t=>{const r=await fixture(t,{protector:{isEncryptionAvailable:()=>false}});assert.equal(r.ready,false);assert.throws(()=>r.draft({description:'x'},owner));assert.equal(fs.readdirSync(r.directory).length,0);});
test('queue bounds do not delete unsent feedback; manual text removes known secrets',async t=>{const r=await fixture(t);const secret='LP1-W-'+'F'.repeat(40);const p=r.preview({description:'故障 '+secret+' token=private https://example.com'},owner);assert.equal(JSON.stringify(p).includes(secret),false);for(let i=0;i<100;i++)r.draft({description:'问题 '+i},owner);assert.throws(()=>r.draft({description:'full'},owner),e=>e.code==='REPORT_LOCAL_FULL');assert.equal(r.records.size,100);});
test('opt-out during credential acquisition cancels an unsubmitted automatic report',async t=>{const r=await fixture(t);r.activate(true);let entered,release;const waiting=new Promise(resolve=>entered=resolve),hold=new Promise(resolve=>release=resolve);r.session=async()=>{entered();await hold;return {token:'synthetic'};};let sent=0;r.post=async()=>{sent++;};const pending=r.request('submit',{report:{kind:'automatic'}});await waiting;r.configure({automatic:false},owner);release();await assert.rejects(pending,e=>e.code==='REPORT_DISABLED');assert.equal(sent,0);});
test('structured errors and accepted-only results are reported without copying business objects',async t=>{const r=await fixture(t);r.activate(true);r.capture('products.batch',null,{results:[{ok:false,error:{code:'CONNECTION_TIMEOUT',message:'private buyer message'},cookie:'sensitive'}]},owner);r.capture('delivery.execute',null,{status:'accepted',text:'private delivery content'},owner);assert.equal(r.list(owner).length,2);const text=JSON.stringify([...r.records.values()]);assert.equal(text.includes('private'),false);assert.equal(text.includes('sensitive'),false);});
