'use strict';
// Decision-value: establish that the new local-claim UI never presents a public
// buyer link, preserves one-time token semantics, and wires inventory multiline
// imports through preview. All records/files belong to a fresh test vault.
const { _electron }=require('playwright-core');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const project=path.resolve(__dirname,'..'),vault=path.join(project,'work',`ui-claims-${Date.now()}`);
fs.mkdirSync(vault,{recursive:true});
const env={...process.env,LIANPU_DATA_DIR:vault};delete env.ELECTRON_RUN_AS_NODE;
let app,page,preview;const checks=[],errors=[];
async function call(action,payload={}){const result=await page.evaluate(({action,payload})=>window.desk.call(action,payload),{action,payload});assert.equal(result.ok,true,JSON.stringify(result.error));return result.data;}
const pass=name=>{checks.push(name);process.stdout.write(`PASS ${name}\n`);};
(async()=>{try{
  app=await _electron.launch({executablePath:path.join(project,'node_modules','electron','dist','electron.exe'),args:[project],env,timeout:30000});page=await app.firstWindow();page.on('pageerror',error=>errors.push(error.message));
  await page.locator('#auth-form [name="name"]').fill('领取核验管理员');await page.locator('#auth-form [name="password"]').fill('Claims-local-passphrase-2026!');await page.locator('#auth-form [name="confirmation"]').fill('Claims-local-passphrase-2026!');await page.locator('#auth-form button[type="submit"]').click();await page.waitForSelector('.shell');await page.locator('#dialog [data-action="close-dialog"]').first().click();
  await page.locator('[data-action="navigate"][data-route="afterSales"]').click();assert.equal(await page.locator('[data-action="claims-open"]').count(),0);assert.equal(await page.locator('[data-action="claims-switch-test"]').count(),1);pass('real workspace offers an explicit move to isolated testing, not a public claim creator');
  await page.locator('#space-select').selectOption('test');await page.locator('[data-action="seed"]').click();await page.locator('[data-action="claims-open"]').click();await page.locator('#dialog [data-action="claims-import"]').waitFor();
  const fixture=path.join(vault,'原创领取试运行说明.txt');fs.writeFileSync(fixture,'本文件由该测试独立生成，仅用于当前电脑验证。\n不是发给真实买家的内容。','utf8');await app.evaluate(({dialog},fixture)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[fixture]});},fixture);
  await page.locator('[data-action="claims-import"]').click();await page.locator('#claim-file-form [name="rightsConfirmed"]').check();await page.locator('#claim-file-form button[type="submit"]').click();await page.locator('[data-action="claims-create"]').waitFor();await page.locator('[data-action="claims-create"]').click();await page.locator('#claim-create-form [name="orderId"]').selectOption('test-order-1');await page.locator('#claim-create-form [name="maxClaims"]').fill('2');await page.locator('#claim-create-form button[type="submit"]').click();await page.locator('[name="claimToken"]').waitFor();const token=await page.locator('[name="claimToken"]').inputValue();assert.match(token,/^[A-Za-z0-9_-]{43}$/);await page.locator('[data-action="claims-back"]').click();assert.ok(!(await page.locator('body').textContent()).includes(token));const grants=await call('claims.grants',{space:'test'});assert.equal(grants.length,1);assert.equal(grants[0].maxClaims,2);assert.equal(grants[0].claimsStarted,0);assert.equal(grants[0].token,undefined);assert.equal(grants[0].tokenHash,undefined);await page.screenshot({path:path.join(__dirname,'ui-claims-overview.png'),fullPage:true});pass('file picker and creation form produce a scoped token shown once, with no token in subsequent listings');
  await page.locator('[data-action="claims-token"]').click();await page.locator('#claim-token-form [name="token"]').fill(token);const opened=app.waitForEvent('window');await page.locator('#claim-token-form button[type="submit"]').click();preview=await opened;await preview.waitForURL(url=>url.hostname==='127.0.0.1');await preview.getByRole('heading',{name:'原创领取试运行说明.txt'}).waitFor();assert.ok((await preview.locator('body').textContent()).includes('不能作为真实买家'));assert.equal(await preview.evaluate(()=>typeof window.desk),'undefined');await preview.close();preview=null;await page.locator('[data-action="claims-back"]').click();await page.locator('[data-action="claims-access"]').click();await page.getByRole('heading',{name:'本机领取请求记录'}).waitFor();assert.ok((await page.locator('#dialog').textContent()).includes('打开领取页面'));assert.equal((await call('claims.grants',{space:'test'}))[0].claimsStarted,0);await page.locator('[data-action="claims-back"]').click();await page.locator('[data-action="claims-revoke"]').click();await page.locator('#claim-revoke-form [name="reason"]').fill('完成本机页面与令牌界面验证');await page.locator('#claim-revoke-form button[type="submit"]').click();await page.locator('[data-action="claims-token"]').waitFor();assert.equal((await call('claims.grants',{space:'test'}))[0].status,'revoked');pass('saved token opens an isolated loopback window; page view is logged without consuming a claim; revoke is real');
  await page.locator('#dialog [data-action="close-dialog"]').first().click();await page.locator('[data-action="navigate"][data-route="data"]').click();await page.locator('#data-kind').selectOption('inventory');await page.locator('[data-action="paste-import"]').click();await page.locator('#csv-form [name="defaultAssetId"]').selectOption('test-asset-unique');await page.locator('#csv-form [name="csv"]').fill('content,costCents\n"一份完整领取资料\n内含多行说明",65');await page.locator('#csv-form button[type="submit"]').click();await page.getByRole('heading',{name:'表格导入预览'}).waitFor();assert.equal((await call('workspace.snapshot',{space:'test'})).inventory.length,3);await page.locator('[data-action="import-confirm"]').click();await page.getByRole('heading',{name:'逐项导入结果'}).waitFor();const inventory=(await call('workspace.snapshot',{space:'test'})).inventory;assert.equal(inventory.length,4);assert.equal(inventory.find(i=>i.content.startsWith('一份完整')).content,'一份完整领取资料\n内含多行说明');pass('inventory CSV chooses a default asset, preserves quoted newlines, and writes only after confirmation');
  assert.deepEqual(errors,[]);const report={verifiedAt:new Date().toISOString(),status:'passed',checks,rendererErrors:errors,vault,screenshots:['ui-claims-overview.png'],scope:'Local files and isolated test orders only; loopback page open, no buyer messages or public hosting'};fs.writeFileSync(path.join(__dirname,'ui-claims-result.json'),JSON.stringify(report,null,2));process.stdout.write(JSON.stringify(report,null,2)+'\n');
}catch(error){process.stderr.write(error.stack+'\n');process.exitCode=1;if(page){try{await page.screenshot({path:path.join(__dirname,'ui-claims-failure.png'),fullPage:true,mask:[page.locator('[name="claimToken"]'),page.locator('[name="token"]')]});}catch{}}}finally{if(preview)try{await preview.close();}catch{}if(app){try{await app.evaluate(({app})=>app.quit());}catch{}try{await app.close();}catch{}}}})();
