'use strict';
// Decision: verify recently changed forms persist to the intended space and do not
// silently ignore controls. Stop on first failure. Uses a new isolated test vault;
// no real account, platform write, model request, notification or file picker.
const { _electron } = require('playwright-core');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const project = path.resolve(__dirname,'..');
const vault = path.join(project,'work',`ui-focused-${Date.now()}`);
fs.mkdirSync(vault,{recursive:true});
const env={...process.env,LIANPU_DATA_DIR:vault};delete env.ELECTRON_RUN_AS_NODE;
let app,page;const issues=[];const passed=[];
async function call(action,payload={}) {const response=await page.evaluate(({action,payload})=>window.desk.call(action,payload),{action,payload});assert.equal(response.ok,true,`${action}: ${JSON.stringify(response.error)}`);return response.data;}
async function nav(route){await page.locator(`[data-action="navigate"][data-route="${route}"]`).first().click();}
async function close(){if(await page.locator('#dialog').isVisible())await page.locator('#dialog [data-action="close-dialog"]').first().click();}
function pass(name){passed.push(name);process.stdout.write(`PASS ${name}\n`);}
(async()=>{
  try{
    app=await _electron.launch({executablePath:path.join(project,'node_modules','electron','dist','electron.exe'),args:[project],env,timeout:30000});page=await app.firstWindow();page.on('pageerror',error=>issues.push(error.message));
    await page.locator('#auth-form [name="name"]').fill('表单核验管理员');await page.locator('#auth-form [name="password"]').fill('Focused-local-passphrase-2026!');await page.locator('#auth-form [name="confirmation"]').fill('Focused-local-passphrase-2026!');await page.locator('#auth-form button[type="submit"]').click();await page.waitForSelector('.shell');await close();
    await page.locator('#space-select').selectOption('test');await page.locator('[data-action="seed"]').click();await page.getByRole('heading',{name:'交付凭条'}).waitFor();
    await nav('settings');await page.locator('#settings-form [name="knowledge"]').fill('这是商家批准公开的答案。\n只讨论本商品的使用方式。');await page.locator('#settings-form [name="aiEndpoint"]').fill('https://example.invalid/v1');await page.locator('#settings-form [name="aiModel"]').fill('local-fixture-model');await page.locator('#settings-form [name="apiKey"]').fill('fixture-secret-not-used');await page.locator('#settings-form [name="minPrice"]').fill('15.50');await page.locator('#settings-form [name="lockMinutes"]').fill('17');assert.equal(await page.locator('#settings-form [name="lockMinutes"]').inputValue(),'17','lockMinutes input before submit');await page.locator('#settings-form button[type="submit"]').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent==='本机设置已保存。');
    let snapshot=await call('workspace.snapshot',{space:'test'});const settings=snapshot.settings.find(r=>r.knowledge);assert.equal(settings.space,'test');assert.equal(settings.minPriceCents,1550);assert.equal(settings.lockMinutes,17,JSON.stringify({settings,preferences:await call('app.preferences.get')}));const model=snapshot.integrations.find(r=>r.type==='ai');assert.equal(model.model,'local-fixture-model');assert.equal(model.enabled,false);assert.equal(model.apiKey,undefined);assert.equal(await page.locator('#settings-form [name="apiKey"]').inputValue(),'');assert.equal((await call('workspace.snapshot',{space:'live'})).integrations.length,0);pass('settings and model configuration persist only in test space; credentials clear and remain hidden');
    await nav('inventory');await page.locator('[data-action="inventory-adjust"]').first().click();await page.locator('#inventory-adjust-form [name="status"]').selectOption('disabled');await page.locator('#inventory-adjust-form [name="reason"]').fill('本次隔离表单核验，停用此条目');await page.locator('#inventory-adjust-form button[type="submit"]').click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);snapshot=await call('workspace.snapshot',{space:'test'});assert.equal(snapshot.inventory[0].status,'disabled');assert.equal(snapshot.inventory[0].adjustments.length,1);pass('inventory adjustment uses supported disabled state and stores its reason');
    await nav('rules');await page.locator('[data-action="edit"][data-kind="rules"]').last().click();await page.locator('[data-action="add-gift"]').click();await page.locator('[name="giftAsset"]').selectOption('test-asset-unique');await page.locator('[name="giftQuantity"]').fill('1');await page.locator('[name="thankYou"]').fill('谢谢购买，使用问题可在此会话联系。');await page.locator('#entity-form button[type="submit"]').click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);snapshot=await call('workspace.snapshot',{space:'test'});assert.deepEqual(snapshot.rules[0].gifts,[{assetId:'test-asset-unique',quantity:1}]);assert.equal(snapshot.rules[0].thankYou,'谢谢购买，使用问题可在此会话联系。');pass('gift rows and merchant thank-you copy persist without enabling automation');
    await call('entity.save',{kind:'rules',record:{id:snapshot.rules[0].id,space:'test',accountId:'test-account-1',enabled:true}});await page.locator('[data-action="rule-test"]').click();await page.locator('#rule-test-form [name="orderId"]').selectOption('test-order-1');await page.locator('#rule-test-form button[type="submit"]').click();await page.getByRole('heading',{name:'交付规则试运行'}).waitFor();assert.equal(await page.locator('#dialog [data-action="delivery-execute"]').count(),0);assert.equal((await call('workspace.snapshot',{space:'test'})).deliveries.length,0);await close();pass('rule trial keeps an eligible order preview free of execution controls and delivery records');
    await nav('statistics');await page.locator('#statistics-form button[type="submit"]').click();await page.waitForTimeout(100);assert.equal((await page.locator('.metric-strip dd').first().textContent()).trim(),'3');pass('statistics date range includes orders throughout the selected UTC end date');
    await nav('assets');await page.locator('[data-action="edit"][data-kind="assets"]').first().click();await page.locator('#entity-form [name="name"]').fill('未保存的敏感草稿');await call('auth.lock');await page.waitForSelector('#auth-form');assert.equal(await page.locator('#dialog').textContent(),'');assert.equal(await page.locator('#media-dialog').textContent(),'');assert.equal(await page.locator('body').textContent().then(s=>s.includes('未保存的敏感草稿')),false);pass('application lock removes both ordinary and material dialogs and unsaved content');
    assert.deepEqual(issues,[]);const report={verifiedAt:new Date().toISOString(),status:'passed',checks:passed,rendererErrors:issues,scope:'Isolated local Electron UI, no external writes',vault};fs.writeFileSync(path.join(__dirname,'ui-focused-result.json'),JSON.stringify(report,null,2));process.stdout.write(JSON.stringify(report,null,2)+'\n');
  }catch(error){process.stderr.write(error.stack+'\n');process.exitCode=1;}finally{if(app){try{await app.evaluate(({app})=>app.quit());}catch{}try{await app.close();}catch{}}}
})();
