'use strict';
// Hypothesis: material selection preserves draft edits, authenticated images render,
// and copying a draft across accounts clears delivery bindings. This isolated test
// checks those user decisions; it never publishes or sends a buyer message.
const { _electron }=require('playwright-core');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const project=path.resolve(__dirname,'..'),vault=path.join(project,'work',`ui-media-${Date.now()}`);
fs.mkdirSync(vault,{recursive:true});
const env={...process.env,LIANPU_DATA_DIR:vault};delete env.ELECTRON_RUN_AS_NODE;
let app,page;const checks=[],errors=[];
async function call(action,payload={}){const r=await page.evaluate(({action,payload})=>window.desk.call(action,payload),{action,payload});assert.equal(r.ok,true,JSON.stringify(r.error));return r.data;}
const pass=name=>{checks.push(name);process.stdout.write(`PASS ${name}\n`);};
(async()=>{try{
  app=await _electron.launch({executablePath:path.join(project,'node_modules','electron','dist','electron.exe'),args:[project],env,timeout:30000});page=await app.firstWindow();page.on('pageerror',error=>errors.push(error.message));
  await page.locator('#auth-form [name="name"]').fill('素材核验管理员');await page.locator('#auth-form [name="password"]').fill('Material-local-passphrase-2026!');await page.locator('#auth-form [name="confirmation"]').fill('Material-local-passphrase-2026!');await page.locator('#auth-form button[type="submit"]').click();await page.waitForSelector('.shell');await page.locator('#dialog [data-action="close-dialog"]').first().click();
  await page.locator('#space-select').selectOption('test');await page.locator('[data-action="seed"]').click();await page.getByRole('heading',{name:'交付凭条'}).waitFor();
  const bytes=await app.evaluate(({nativeImage})=>nativeImage.createFromBitmap(Buffer.from([45,100,70,255,255,255,255,255,255,255,255,255,45,100,70,255]),{width:2,height:2}).toPNG().toString('base64'));const imagePath=path.join(vault,'原创测试几何.png');fs.writeFileSync(imagePath,Buffer.from(bytes,'base64'));
  await app.evaluate(({dialog},imagePath)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[imagePath]});},imagePath);
  await page.locator('[data-action="navigate"][data-route="products"]').click();await page.locator('[data-action="edit"][data-kind="products"][data-id="test-product-1"]').click();await page.locator('#entity-form [name="title"]').fill('仍在编辑的原创商品标题');
  await page.locator('[data-action="media-pick"]').click();await page.locator('#media-dialog [data-action="media-import"]').click();await page.locator('#media-dialog .media-item img').waitFor();await page.waitForFunction(()=>{const img=document.querySelector('#media-dialog .media-item img');return img&&img.complete&&img.naturalWidth===2;});await page.locator('#media-dialog [data-media-check]').check();await page.locator('#media-dialog [data-action="media-use"]').click();assert.equal(await page.locator('#entity-form [name="title"]').inputValue(),'仍在编辑的原创商品标题');assert.match(await page.locator('#entity-form [name="images"]').inputValue(),/^lianpu:\/\/app\/media\//);await page.locator('#entity-form button[type="submit"]').click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);pass('native material import renders authenticated image and preserves unsaved product form');
  const target=await call('entity.save',{kind:'accounts',record:{space:'test',name:'目标测试账号',paused:true}});await page.locator('[data-action="reload"]').click();await page.locator('[data-action="clone-account"][data-id="test-product-1"]').click();await page.locator('#clone-account-form [name="targetAccountId"]').selectOption(target.id);await page.locator('#clone-account-form [name="rightsConfirmed"]').check();await page.locator('#clone-account-form button[type="submit"]').click();await page.getByRole('heading',{name:'目标账号本地草稿'}).waitFor();const snapshot=await call('workspace.snapshot',{space:'test',accountId:target.id});assert.equal(snapshot.products.length,1);assert.equal(snapshot.products[0].status,'draft');assert.ok(snapshot.products[0].variants.every(v=>!v.assetId));assert.equal(snapshot.products[0].images.length,1);pass('cross-account copy creates a local draft and requires new asset bindings');
  assert.deepEqual(errors,[]);const report={verifiedAt:new Date().toISOString(),status:'passed',checks,rendererErrors:errors,vault,scope:'Isolated native material picker and local draft copy only; no external writes'};fs.writeFileSync(path.join(__dirname,'ui-media-result.json'),JSON.stringify(report,null,2));process.stdout.write(JSON.stringify(report,null,2)+'\n');
}catch(error){process.stderr.write(error.stack+'\n');process.exitCode=1;}finally{if(app){try{await app.evaluate(({app})=>app.quit());}catch{}try{await app.close();}catch{}}}})();
