'use strict';
const {createHash}=require('node:crypto');
const stable=(account,kind,external)=>'xy-'+createHash('sha256').update(account+'\0'+kind+'\0'+external).digest('hex').slice(0,40);
function identifier(value){if(typeof value==='number'&&!Number.isSafeInteger(value))throw new Error('平台标识精度不安全');if(!['string','number'].includes(typeof value))throw new Error('平台标识缺失');const text=String(value);if(!text||text.length>200||/[\x00-\x20]/.test(text))throw new Error('平台标识无效');return text;}
function timestamp(value){if(typeof value==='number'||/^\d{10,13}$/.test(value||'')){const n=Number(value);return new Date(n<1e12?n*1000:n).toISOString();}if(typeof value==='string'&&Number.isFinite(Date.parse(value)))return new Date(value).toISOString();throw new Error('平台时间缺失');}
function cents(value){if(typeof value==='number'&&Number.isSafeInteger(value)&&value>=0)return value;throw new Error('平台金额未能精确解析');}
function price(value){if(typeof value!=='string'||!/^\d+(\.\d{1,2})?$/.test(value))throw new Error('平台价格格式未确认');const [whole,fraction='']=value.split('.');return cents(Number(whole)*100+Number(fraction.padEnd(2,'0')));}
function identity(user,profile){const id=identifier(user?.userId);if(user?.mainUserId&&identifier(user.mainUserId)!==id)throw new Error('暂不支持子账号代替本人身份');const base=profile?.module?.base;if(!base?.displayName||typeof base.displayName!=='string')throw new Error('平台昵称尚未核验');return {platformUserId:id,nickname:base.displayName.slice(0,100),avatarUrl:typeof base.avatar==='string'&&/^https:\/\//.test(base.avatar)?base.avatar:undefined};}
function product(card){const c=card?.cardData||card;const externalId=identifier(c?.id||c?.itemId);if(typeof c.title!=='string'||!c.title)throw new Error('商品标题缺失');let amount=c.priceCents;if(amount==null){const values=typeof c.priceInfo==='object'?[c.priceInfo?.price,c.priceInfo?.value,c.priceInfo?.priceText]:[c.priceInfo];const explicit=values.find(v=>typeof v==='string'&&/^\d+(\.\d{1,2})?$/.test(v));amount=price(explicit);}return {externalId,title:c.title,priceCents:cents(amount),...(Number.isSafeInteger(c.stock)&&c.stock>=0?{stock:c.stock}:{}),variants:[]};}
function conversation(raw,accountId,ownId){const s=raw?.session||raw;const externalId=identifier(s?.sessionId);const owner=identifier(s?.ownerInfo?.userId),peer=identifier(s?.userInfo?.userId);if(owner!==ownId&&peer!==ownId)throw new Error('会话不属于此账号');const buyerId=owner===ownId?peer:owner;if(buyerId===ownId)throw new Error('会话接收方未确认');return {id:stable(accountId,'conversation',externalId),externalId,buyerId,buyerName:String((owner===ownId?s.userInfo:s.ownerInfo)?.nick||''),manual:false,unread:Number.isSafeInteger(s.unread)?s.unread:0};}
function message(raw,conv,ownId){const externalId=identifier(raw?.messageId||safeJson(raw?.extJson)?.messageId);const sender=identifier(raw?.senderInfo?.userId||raw?.senderId);if(sender!==conv.buyerId&&sender!==ownId)throw new Error('消息发送方不属于会话');const text=raw?.content?.text?.text;if(typeof text!=='string'||!text||text.length>10000)throw new Error('此消息类型暂不支持文本同步');return {externalId,conversationId:conv.id,buyerId:conv.buyerId,text,direction:sender===ownId?'outgoing':'incoming',status:sender===ownId?'sent':'received',receiptId:sender===ownId?externalId:undefined,receivedAt:timestamp(raw.timeStamp||raw.createAt),origin:'platform'};}
function safeJson(s){try{return typeof s==='string'?JSON.parse(s):s||{};}catch{return {};}}
// Payment/refund facts require explicit fields from the authenticated per-order
// detail response. A list title, chat text or a generic successful HTTP result is
// never sufficient to infer payment, absence of refund, or buyer identity.
function order(data,requestedId,ownId,verifiedAt,evidenceId){const o=data?.order||data?.orderInfo||data;const externalId=identifier(o?.orderId||o?.tid);if(externalId!==requestedId||identifier(o.sellerId)!==ownId)throw new Error('订单身份不匹配');const buyerId=identifier(o.buyerId);if(!['unpaid','paid','refunded','partially_refunded'].includes(o.paymentStatus)||!['open','paid','shipped','completed','refunding','refunded','closed','cancelled'].includes(o.tradeStatus))throw new Error('平台付款或退款状态结构尚未核验');const amountCents=cents(o.amountCents),refundCents=cents(o.refundCents);if(refundCents>amountCents)throw new Error('退款金额不一致');return {externalId,buyerId,...(o.itemId||o.productId?{productExternalId:identifier(o.itemId||o.productId)}:{}),buyerName:String(o.buyerName||''),amountCents,refundCents,paymentStatus:o.paymentStatus,tradeStatus:o.tradeStatus,...(o.paidAt?{paidAt:timestamp(o.paidAt)}:{}),verifiedAt,evidenceId,source:'platform'};}
function orderIds(data){const out=new Set();function visit(value,depth){if(!value||typeof value!=='object'||depth>8)return;if(Array.isArray(value)){value.slice(0,100).forEach(x=>visit(x,depth+1));return;}for(const [key,v]of Object.entries(value)){if(['orderId','bizOrderId','tradeId','tid'].includes(key)){try{out.add(identifier(v));}catch{}}else if(typeof v==='object')visit(v,depth+1);}}visit(data,0);return [...out].slice(0,30);}
module.exports={identifier,timestamp,cents,price,identity,product,conversation,message,order,orderIds,stable};
