'use strict';
const {createHash,randomUUID}=require('node:crypto');
const {AccountQueue}=require('./queue.cjs');const {SessionVault}=require('./session-vault.cjs');const {OfficialPageAdapter}=require('./official-page.cjs');const normal=require('./normalize.cjs');const {ReadCursorSync}=require('./read-sync.cjs');
const HOME_URL='https://www.goofish.com/';const LOGIN_URL='https://www.goofish.com/login?redirectURL=https%3A%2F%2Fwww.goofish.com%2Fim';const IM_URL='https://www.goofish.com/im';
const NAVIGATION_HOSTS=new Set(['www.goofish.com','goofish.com','login.taobao.com','login.m.taobao.com','passport.goofish.com']);
const BLOCK_REASON='此账号尚未完成本人扫码及逐项会话能力核验。';
const CAPABILITY_LABELS={readProducts:'读取商品',readOrders:'读取订单',readMessages:'读取消息',sendMessages:'发送消息',publishProducts:'发布商品',updateProducts:'维护商品',markShipped:'标记发货',refunds:'执行退款',logistics:'提交物流',promotions:'运营任务',interactions:'买家互动'};
function accountKey(account){const id=typeof account==='string'?account:account?.id||account?.accountId;if(typeof id!=='string'||!id.trim()||id.length>256)throw new TypeError('需要有效账号标识');return id;}
function partitionFor(account){return 'lianpu-xianyu-'+createHash('sha256').update(accountKey(account)).digest('hex');}
function isAllowedNavigation(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&(!u.port||u.port==='443')&&NAVIGATION_HOSTS.has(u.hostname);}catch{return false;}}
function frameAllowed(value){return isAllowedNavigation(value)||value.startsWith('https://g.alicdn.com/platform/xdomain-storage/0.2.4/frame.html');}
function capabilities(){return Object.fromEntries(Object.entries(CAPABILITY_LABELS).map(([key,label])=>{const implemented=['readProducts','readOrders','readMessages','sendMessages'].includes(key);return [key,{label,available:false,verified:false,status:implemented?'unverified':'unsupported',reason:implemented?'尚未检查此项，可检查登录并同步。':'当前版本尚未接入此平台操作，请在闲鱼 App 处理；重复扫码不会启用。',verifiedAt:null,evidenceId:null}];}));}
function blocked(operation,reason=BLOCK_REASON){return {status:'blocked',operation,reason,verified:false,source:'platform',receiptId:null};}
const iso=()=>new Date().toISOString();const terminal=new Set(['cancelled','expired','failed','bound']);
class XianyuConnector {
 constructor({electron,onStatus=()=>{},onEvents=()=>{},authorizeTask=()=>true,adapterFactory,queueCapacity=40,pollMs=1500,attemptMs=180000}={}){Object.assign(this,{electron,onStatus,onEvents,authorizeTask,queueCapacity,pollMs,attemptMs});this.adapterFactory=adapterFactory||((win)=>new OfficialPageAdapter(win));this.records=new Map();this.windows=new Map();this.sessions=new Map();this.adapters=new Map();this.attempts=new Map();this.queues=new Map();this.revocations=new Map();this.accountGenerations=new Map();this.timers=new Map();this.pauseGeneration=0;this.vault=new SessionVault(electron||{});this.dedupe=new Map();this.receipts=new Map();this.reader=new ReadCursorSync();this.inspections=new Map();}
 _generation(id){return this.accountGenerations.get(id)||0;}
 _queue(id){if(!this.queues.has(id))this.queues.set(id,new AccountQueue({capacity:this.queueCapacity}));return this.queues.get(id);}
 capabilities(account){return structuredClone(this.records.get(accountKey(account))?.capabilities||capabilities());}
 status(account){const id=accountKey(account),r=this.records.get(id)||{};return structuredClone({accountId:id,loginStatus:'unverified',connectionStatus:'disconnected',connectionState:'unverified',browserState:'closed',automationState:'paused',sessionVersion:0,reason:BLOCK_REASON,...r,capabilities:r.capabilities||capabilities(),queue:this.queues.get(id)?.status()||{pending:0,inFlight:0,capacity:this.queueCapacity,paused:true}});}
 _set(id,fields){this.records.set(id,{...(this.records.get(id)||{}),...fields,checkedAt:iso()});const status=this.status(id);try{this.onStatus(status);}catch{}return status;}
 _cap(id,name,ok,reason,evidenceId){const caps=this.capabilities(id);caps[name]={...caps[name],available:ok,verified:ok,status:ok?'verified':'unavailable',reason:reason||'',checkedAt:iso(),verifiedAt:ok?iso():null,evidenceId:ok?evidenceId:null,sessionVersion:this.status(id).sessionVersion,sessionGeneration:this.status(id).sessionVersion};this._set(id,{capabilities:caps});}
 _session(id){if(this.sessions.has(id))return this.sessions.get(id);const s=this.electron.session.fromPartition(partitionFor(id),{cache:false});s.setPermissionRequestHandler((_w,_p,cb)=>cb(false));s.setPermissionCheckHandler(()=>false);s.setDevicePermissionHandler?.(()=>false);s.setDisplayMediaRequestHandler?.((_r,cb)=>cb({}));s.on('will-download',e=>e.preventDefault());s.webRequest.onBeforeRequest({urls:['<all_urls>']},(d,cb)=>{const secure=/^(https:|wss:)/.test(d.url);cb({cancel:!secure||(d.resourceType==='mainFrame'&&!isAllowedNavigation(d.url))||(d.resourceType==='subFrame'&&!frameAllowed(d.url))});});this.sessions.set(id,s);return s;}
 _window(id,{show=false}={}){const current=this.windows.get(id);if(current&&!current.isDestroyed())return current;if(!this.electron?.BrowserWindow)throw new Error('扫码登录仅能在桌面程序中进行');const win=new this.electron.BrowserWindow({width:1120,height:820,minWidth:720,minHeight:560,title:'闲鱼官方扫码 · 请使用本人账号',autoHideMenuBar:true,show:false,webPreferences:{session:this._session(id),nodeIntegration:false,nodeIntegrationInWorker:false,nodeIntegrationInSubFrames:false,contextIsolation:true,sandbox:true,webSecurity:true,allowRunningInsecureContent:false,experimentalFeatures:false,webviewTag:false,devTools:false,safeDialogs:true,navigateOnDragDrop:false,backgroundThrottling:false}});this.windows.set(id,win);this.adapters.set(id,this.adapterFactory(win,id));const guard=(e,u)=>{const url=typeof u==='string'?u:u?.url||e.url;if(!frameAllowed(url))e.preventDefault();};win.webContents.on('will-navigate',guard);win.webContents.on('will-redirect',guard);win.webContents.on('will-frame-navigate',guard);win.webContents.on('will-attach-webview',e=>e.preventDefault());win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('page-title-updated',e=>e.preventDefault());win.webContents.on('did-fail-load',(_e,code,_d,_u,main)=>{if(main&&code!==-3)this._set(id,{browserState:'load_failed',reason:'官方页面未能载入，请检查网络后重试'});});win.on('closed',()=>{for(const [key,value]of this.windows)if(value===win){this.windows.delete(key);this.adapters.delete(key);this._set(key,{browserState:'closed',connectionStatus:'disconnected',connectionState:'disconnected'});}const attempt=[...this.attempts.values()].find(a=>a.window===win&&!terminal.has(a.state));if(attempt)this._cancel(attempt,'cancelled','本人已关闭扫码窗口');});if(show)win.once('ready-to-show',()=>{if(!win.isDestroyed())win.show();});return win;}
 _publicAttempt(a){return structuredClone({attemptId:a.attemptId,memberId:a.memberId,accountId:a.accountId||null,targetAccountId:a.accountId||null,state:a.state,status:a.state,loginStatus:a.state,reason:a.reason||'',createdAt:a.createdAt,expiresAt:a.expiresAt,qrVisible:!!a.qrVisible,observedStates:a.observedStates||[],identity:a.identity||null,verifiedAt:a.verifiedAt||null,evidenceId:a.evidenceId||null,sessionGeneration:a.sessionGeneration||0});}
 _attemptUpdate(a,state,reason){if(terminal.has(a.state))return;Object.assign(a,{state,reason});if(!a.observedStates.includes(state))a.observedStates.push(state);this._set(a.key,{attemptId:a.attemptId,loginStatus:state,browserState:'page_open',reason});}
 async startLogin({memberId,accountId,expectedIdentity,generation}={}){if(typeof memberId!=='string'||!memberId)throw new Error('登录尝试必须绑定发起成员');if(accountId)accountKey(accountId);if([...this.attempts.values()].filter(a=>!terminal.has(a.state)&&a.memberId!==memberId).length>=5)throw new Error('同时最多开启5个扫码尝试');for(const a of this.attempts.values())if(a.memberId===memberId&&a.accountId===accountId&&!terminal.has(a.state))this._cancel(a,'cancelled','新的扫码尝试已取代旧尝试');const pauseGeneration=this.pauseGeneration,targetGeneration=accountId?this._generation(accountId):0;if(accountId&&this.revocations.has(accountId))await this.revocations.get(accountId);if(pauseGeneration!==this.pauseGeneration||targetGeneration!==(accountId?this._generation(accountId):0))return {state:'cancelled',status:'cancelled',reason:'账号或工作区状态已改变'};const attemptId=randomUUID(),key='attempt-'+attemptId;const a={attemptId,key,memberId,accountId,expectedIdentity:typeof expectedIdentity==='object'?expectedIdentity.platformUserId:expectedIdentity,generation,pauseGeneration,targetGeneration,state:'opening',createdAt:iso(),expiresAt:new Date(Date.now()+this.attemptMs).toISOString(),observedStates:['opening']};this.attempts.set(attemptId,a);a.window=this._window(key,{show:true});try{await a.window.loadURL(LOGIN_URL);if(!terminal.has(a.state)){this._attemptUpdate(a,'waiting_scan','请使用闲鱼 APP 扫描官方页面二维码');void this._observe(a);a.timer=setInterval(()=>void this._observe(a),this.pollMs);a.timer.unref?.();}}catch{this._cancel(a,'failed','官方登录页面未能载入，请重试');}return this._publicAttempt(a);}
 getLogin({attemptId,memberId}={}){const a=this.attempts.get(attemptId);if(!a||a.memberId!==memberId)throw new Error('登录尝试不存在或不属于当前成员');return this._publicAttempt(a);}
 _valid(a){return !terminal.has(a.state)&&a.pauseGeneration===this.pauseGeneration&&a.targetGeneration===(a.accountId?this._generation(a.accountId):0)&&!a.window.isDestroyed();}
 async _observe(a){if(a.observing||!this._valid(a)||a.state==='success')return;a.observing=true;try{if(Date.now()>=Date.parse(a.expiresAt)){this._cancel(a,'expired','二维码尝试已过期，请重新开始');return;}const frames=a.window.webContents.mainFrame?.framesInSubtree||[];for(const frame of frames){if(!/^https:\/\/passport\.goofish\.com\//.test(frame.url||''))continue;const view=await frame.executeJavaScript(`(()=>{const text=document.body?.innerText||'';const visible=e=>!!(e&&e.getBoundingClientRect().width>0&&e.getBoundingClientRect().height>0);return {expired:/二维码.{0,6}(失效|过期)/.test(text),scanned:/(扫码成功|扫描成功|请在手机上确认|已扫码)/.test(text),verification:/(拖动滑块|安全验证|完成验证)/.test(text),qr:[...document.querySelectorAll('canvas,img')].some(e=>visible(e)&&(/qr|二维码/i.test(e.className+' '+e.id+' '+e.alt)||e.tagName==='CANVAS'))}})()`);if(!this._valid(a))return;if(view.expired){this._cancel(a,'expired','官方页面显示二维码已过期');return;}a.qrVisible=view.qr;if(view.verification)this._attemptUpdate(a,'verification_required','请在官方页面完成平台要求的人工验证');else if(view.scanned)this._attemptUpdate(a,'scanned','官方页面已显示扫码成功，请在手机上确认');}
 const url=a.window.webContents.getURL?.()||a.window.url||'';if(!url.startsWith(IM_URL)&&!/^https:\/\/www\.goofish\.com\/$/.test(url))return;const adapter=this.adapters.get(a.key);const user=await adapter.request('identity');if(!this._valid(a))return;if(user.status!=='ok'){if(user.status==='verification_required')this._attemptUpdate(a,user.status,user.reason);return;}const profile=await adapter.request('profile');if(!this._valid(a))return;if(profile.status!=='ok')return;let identity;try{identity=normal.identity(user.data,profile.data);}catch{this._attemptUpdate(a,'verification_required','平台身份未能完整核验，请确认本人主账号');return;}if(a.expectedIdentity&&a.expectedIdentity!==identity.platformUserId){this._cancel(a,'failed','扫码账号与原绑定身份不同，已拒绝覆盖');return;}Object.assign(a,{identity,verifiedAt:iso(),evidenceId:'xy-identity-'+randomUUID(),sessionGeneration:Math.max(Date.now(),Number(a.generation||0)+1)});this._attemptUpdate(a,'success','本人身份已核验，请回联铺保存账号资料');clearInterval(a.timer);a.window.hide?.();}catch{if(this._valid(a))this._attemptUpdate(a,'verification_required','官方页面结构或连接发生变化，请检查官方窗口');}finally{a.observing=false;}}
 _cancel(a,state,reason){if(terminal.has(a.state))return this._publicAttempt(a);a.state=state;a.reason=reason;a.observedStates.push(state);delete a.identity;clearInterval(a.timer);if(a.window&&!a.window.isDestroyed())a.window.destroy();this._set(a.key,{attemptId:a.attemptId,loginStatus:state,connectionStatus:'disconnected',browserState:'closed',reason});const s=this.sessions.get(a.key);if(s)void Promise.allSettled([s.closeAllConnections(),s.clearStorageData(),s.clearCache()]);return this._publicAttempt(a);}
 cancelLogin(input){this.getLogin(input);return this._cancel(this.attempts.get(input.attemptId),'cancelled','本人已取消扫码尝试');}
 async bindLogin({attemptId,memberId,accountId}={}){this.getLogin({attemptId,memberId});accountKey(accountId);const a=this.attempts.get(attemptId);if(Date.now()>=Date.parse(a.expiresAt)){this._cancel(a,'expired','登录确认已过期，请重新扫码');throw new Error('登录确认已过期');}if(a.state!=='success'||!this._valid(a)||!a.identity)throw new Error('扫码尚未成功或尝试已失效');if(a.accountId&&a.accountId!==accountId)throw new Error('重新登录不能修改目标账号');const old=this.records.get(accountId);if(old?.identity?.platformUserId&&old.identity.platformUserId!==a.identity.platformUserId)throw new Error('不能覆盖已绑定的其他平台身份');const adapter=this.adapters.get(a.key),session=this.sessions.get(a.key);const oldWin=this.windows.get(accountId);if(oldWin&&!oldWin.isDestroyed())oldWin.destroy();this._queue(accountId).pause();await this._queue(accountId).drain();if(!this._valid(a))throw new Error('绑定期间登录已取消');this.windows.delete(a.key);this.adapters.delete(a.key);this.sessions.delete(a.key);this.windows.set(accountId,a.window);this.adapters.set(accountId,adapter);this.sessions.set(accountId,session);a.state='bound';a.boundAccountId=accountId;clearInterval(a.timer);this._queue(accountId).resume();a.sessionGeneration=Math.max(a.sessionGeneration,Number(old?.sessionVersion||0)+1);const identity=structuredClone(a.identity);this._set(accountId,{identity,externalId:identity.platformUserId,attemptId,loginStatus:'connected',connectionStatus:'unverified',connectionState:'unverified',browserState:'background',automationState:'paused',sessionVersion:a.sessionGeneration,sessionGeneration:a.sessionGeneration,verifiedAt:a.verifiedAt,evidenceId:a.evidenceId,capabilities:capabilities(),reason:'本人身份已核验；请保存资料、配置规则并明确开启托管'});try{await this.vault.save(accountId,session);}catch{this._set(accountId,{persistenceState:'not_saved',reason:'登录仅保留至本次退出；本机加密会话未能保存'});}return {accountId,identity,externalId:identity.platformUserId,sessionVersion:a.sessionGeneration,sessionGeneration:a.sessionGeneration,verifiedAt:a.verifiedAt,evidenceId:a.evidenceId,capabilities:this.capabilities(accountId)};}
 async openLogin(account,options={}){const id=accountKey(account);const a=await this.startLogin({memberId:options.memberId||options.actorId||'local-owner',accountId:id,expectedIdentity:typeof account==='object'?account.externalId:undefined,...options});return {...this.status(id),...a};}
 async _identityCheck(id,expected){const generation=this._generation(id);const adapter=this.adapters.get(id);if(!adapter)return blocked('session','请先扫码连接此账号');const r=await adapter.request('identity');if(generation!==this._generation(id))return blocked('session','账号状态已改变');if(r.status!=='ok'){this._set(id,{loginStatus:r.status,connectionStatus:'disconnected',connectionState:r.status,reason:r.reason,capabilities:capabilities()});return r;}let actual;try{actual=normal.identifier(r.data?.userId);}catch{return blocked('session','平台返回的身份格式无法确认');}if(!expected||actual!==expected){this._set(id,{loginStatus:'identity_mismatch',connectionStatus:'disconnected',capabilities:capabilities(),reason:'会话身份不匹配，已停止此账号任务'});return blocked('session','会话身份不匹配');}return {status:'ok',identity:actual};}
 _run(account,operation,fn,extraAuthorize){const id=accountKey(account),generation=this._generation(id),sessionVersion=this.status(id).sessionVersion;return this._queue(id).run(async context=>{const identity=this.records.get(id)?.identity?.platformUserId;const checked=await this._identityCheck(id,identity);if(checked.status!=='ok')return checked;if(!context.valid()||generation!==this._generation(id)||sessionVersion!==this.status(id).sessionVersion)return blocked(operation,'账号授权或会话已变化');return fn({...context,id,identity,adapter:this.adapters.get(id)});},{authorize:async()=>{if(generation!==this._generation(id))return false;if(typeof extraAuthorize==='function'&&!(await extraAuthorize()))return false;return this.authorizeTask({accountId:id,operation,sessionVersion});}});}
 async _sessions(adapter,id,identity){const response=await adapter.sessions(identity);if(response.status!=='ok')return response;if(!Array.isArray(response.data?.sessions))return {status:'unavailable',reason:'平台会话结构不兼容，已保留上次资料'};const conversations=[];for(const raw of response.data.sessions){try{conversations.push(normal.conversation(raw,id,identity));}catch{}}return {status:'ok',conversations,raw:response.data.sessions,hasMore:!!response.data.hasMore};}
 async sync(account,kind,{authorize}={}){if(!['products','orders','messages'].includes(kind))throw new Error('同步类型无效');const ready=await this.ensureReadSession(account,authorize);if(ready.status!=="ok")return ready;return this._run(account,'sync:'+kind,async context=>{const {id,identity,adapter,valid}=context;const result=await this.reader.run({...context,kind});if(!valid())return blocked('sync:'+kind,'同步完成前账号状态已改变');const capability={products:'readProducts',orders:'readOrders',messages:'readMessages'}[kind],evidenceId='xy-read-'+randomUUID();this._cap(id,capability,result.status==='ok',result.reason,evidenceId);if(result.status!=='ok'){if(['disconnected','login_required','verification_required','identity_mismatch'].includes(result.status))this._set(id,{connectionStatus:result.status,connectionState:result.status,...(['login_required','verification_required','identity_mismatch'].includes(result.status)?{loginStatus:result.status}:{}),reason:result.reason||'官方消息连接尚未完成认证'});return result;}const connection=await adapter.connection(identity);if(!valid())return blocked('sync:'+kind,'连接核验前账号状态已改变');this._set(id,{connectionStatus:connection.status,connectionState:connection.status});this._cap(id,'sendMessages',connection.status==='connected'&&connection.sendSupported===true,'',evidenceId);try{await this.vault.save(id,this._session(id),this.reader.export(id));}catch{}return {...result,verifiedAt:iso(),evidenceId};},authorize);}
 async sendMessage(request){const {account}=request,id=accountKey(account),key=request.idempotencyKey;if(typeof key!=='string'||!key||key.length>200)return blocked('sendMessages','缺少持久发送标识');const duplicate=this.receipts.get(id+'\0'+key);if(duplicate)return structuredClone(duplicate);return this._run(account,'sendMessages',async({identity,adapter,valid,authorize,markSubmitted})=>{const prior=this.receipts.get(id+'\0'+key);if(prior)return prior;const buyerId=request.conversation?.buyerId||request.order?.buyerId||request.buyerId;if(typeof buyerId!=='string'||typeof request.text!=='string'||!request.text.trim()||request.text.length>10000)return blocked('sendMessages','买家或消息内容不完整');if(request.conversation?.accountId&&request.conversation.accountId!==id||request.order?.accountId&&request.order.accountId!==id)return blocked('sendMessages','跨账号发送已拒绝');const sessions=await this._sessions(adapter,id,identity);if(sessions.status!=='ok')return sessions;const candidates=sessions.conversations.filter(c=>c.buyerId===buyerId);if(candidates.length!==1)return blocked('sendMessages','买家会话未唯一核验，请在官方页面确认会话');const recipient=await adapter.prepareRecipient({identity,buyerId,sessionId:candidates[0].externalId});if(recipient?.status!=='ok')return blocked('sendMessages','官方会话接收方未能核验');const connection=await adapter.connection(identity);if(connection.status!=='connected'||!connection.sendSupported)return blocked('sendMessages','消息连接未认证或官方发送模块不可用');if(!valid()||!(await authorize())||!valid())return blocked('sendMessages','发送前权限或账号状态已变化');markSubmitted();const pending={status:'unknown',source:'platform',receiptId:null,reason:'消息已进入提交阶段，必须取得回执后确认'};this.receipts.set(id+'\0'+key,pending);const r=await adapter.send({identity,buyerId,sessionId:candidates[0].externalId,text:request.text,key,recipient});let settled=r?.status==='blocked'?blocked('sendMessages','提交入口再次核验未通过，消息未提交'):{status:'unknown',source:'platform',receiptId:null,reason:'提交后未取得匹配消息回执，请核验官方聊天后再决定是否补发'};if(r?.status==='accepted'&&typeof r.receiptId==='string'&&r.receiptId&&r.uuid===key){settled={status:'accepted',source:'platform',receiptId:r.receiptId,reason:'官方服务已受理；正在核验已保存消息，不应重复发送'};const check=await adapter.messages(identity,candidates[0].externalId);if(check.status==='ok'&&Array.isArray(check.data?.messages)){const confirmed=check.data.messages.some(raw=>{try{const msg=normal.message(raw,candidates[0],identity);return msg.externalId===r.receiptId&&msg.direction==='outgoing'&&msg.text===request.text;}catch{return false;}});if(confirmed)settled={status:'sent',source:'platform',receiptId:r.receiptId,evidenceId:'xy-send-'+randomUUID(),verifiedAt:iso(),reason:'官方消息历史回查已确认本次消息编号、本人发送方及接收会话'};}}this.receipts.set(id+'\0'+key,settled);return settled;},request.authorize);}
 pause(account,reason='本人已暂停此账号'){const id=accountKey(account);this.accountGenerations.set(id,this._generation(id)+1);this._queue(id).pause();clearInterval(this.timers.get(id));this.timers.delete(id);for(const a of this.attempts.values())if(a.accountId===id&&!terminal.has(a.state))this._cancel(a,'cancelled',reason);const w=this.windows.get(id),generation=this._generation(id);const close=()=>{if(generation===this._generation(id)&&w&&!w.isDestroyed())w.destroy();};if(this._queue(id).active)void this._queue(id).drain().then(close);else close();return this._set(id,{automationState:'paused',connectionStatus:'disconnected',connectionState:'disconnected',browserState:'closed',capabilities:capabilities(),reason});}
 async resume(account,{readOnly=false,authorize}={}){
  const id=accountKey(account);
  const expected=(typeof account==='object'?(account.platformUserId||account.externalId):null)||this.records.get(id)?.identity?.platformUserId;
  if(!expected)return this._set(id,{automationState:'paused',reason:BLOCK_REASON});
  // A resumed connection owns a new lifecycle. Old pause callbacks may finish,
  // but they cannot close this lifecycle or invalidate its new page.
  const generation=this._generation(id)+1;this.accountGenerations.set(id,generation);
  const permitted=async()=>{if(generation!==this._generation(id))return false;try{if(!authorize||await authorize())return generation===this._generation(id);}catch{}if(generation===this._generation(id))this.pause(id,"本次检查权限已改变，已停止读取");return false;};
  const queue=this._queue(id),previousWindow=this.windows.get(id);queue.pause();
  await queue.drain();
  if(!(await permitted()))return this.status(id);
  if(this.revocations.has(id))await this.revocations.get(id);
  if(!(await permitted()))return this.status(id);
  const session=this._session(id);
  if(!this.records.get(id)?.identity){
   let restored;try{restored=await this.vault.restore(id,session);}catch{}
   if(!(await permitted()))return this.status(id);
   if(restored?.progress)this.reader.restore(id,restored.progress);
   if(readOnly&&!restored?.restored)return this._set(id,{sessionVersion:account.sessionVersion,loginStatus:'unverified',automationState:'paused',reason:'未能恢复此账号的本机会话，请检查本机保存状态或重新扫码；原资料已保留'});
  }
  if(!(await permitted()))return this.status(id);
  this._set(id,{identity:{platformUserId:expected,nickname:account.nickname||account.name||''},sessionVersion:(typeof account==='object'?account.sessionVersion:0)||this.status(id).sessionVersion||Date.now(),loginStatus:'checking',connectionStatus:'connecting',connectionState:'connecting',browserState:'loading',automationState:readOnly?'paused':'starting',readOnlyCheck:readOnly,capabilities:capabilities(),reason:'正在核验本人会话'});
  // onStatus is synchronous and may revoke this account. Recheck before
  // creating any page; otherwise a paused account could retain a hidden page.
  if(!(await permitted()))return this.status(id);
  if(previousWindow&&!previousWindow.isDestroyed())previousWindow.destroy();
  if(!(await permitted()))return this.status(id);
  queue.resume();const win=this._window(id);
  try{await win.loadURL(IM_URL);}catch{if(!(await permitted()))return this.status(id);return this.pause(id,'官方消息页面加载失败');}
  if(!(await permitted()))return this.status(id);
  const result=await this._identityCheck(id,expected);
  if(!(await permitted()))return this.status(id);
  if(result.status!=='ok')return this._set(id,{automationState:'paused',reason:result.reason});
  const connection=await this.waitForConnection(this.adapters.get(id),expected,permitted);
  if(!(await permitted()))return this.status(id);
  this._set(id,{loginStatus:'authenticated',automationState:readOnly?'paused':'running',browserState:'background',connectionStatus:connection.status,connectionState:connection.status,reason:readOnly?'登录已核验，本次仅检查连接，托管保持暂停':connection.status==='connected'?'账号托管已开启':'登录已核验，消息连接等待认证'});
  if(!(await permitted()))return this.status(id);
  if(!readOnly&&connection.status==='connected')this._cap(id,'sendMessages',connection.sendSupported===true,'','xy-connection-'+randomUUID());
  return this.status(id);
 }
 async ensureReadSession(account,authorize){
  const id=accountKey(account);
  if(this.adapters.has(id)&&!this.windows.get(id)?.isDestroyed()&&!this._queue(id).closed)return {status:'ok'};
  if(typeof account!=='object'||!account.platformUserId||!account.sessionVersion||account.archived||['cleared','revoked','cleanup_failed','revocation_failed'].includes(account.loginStatus))return blocked('read','此账号尚无可恢复的本人登录，请先扫码绑定');
  if(!this.inspections.has(id)){
   const task=this.resume(account,{readOnly:true,authorize}).finally(()=>{if(this.inspections.get(id)===task)this.inspections.delete(id);});
   this.inspections.set(id,task);
  }
  const result=await this.inspections.get(id);
  return ['authenticated','connected'].includes(result.loginStatus)?{status:'ok'}:blocked('read',result.reason);
 }
 async waitForConnection(adapter,identity,valid){
  // Poll the already loaded SDK's local state only; do not retry remote writes.
  for(let attempt=0;attempt<9;attempt++){
   if(!(await valid()))return {status:'disconnected'};
   const status=await adapter.connection(identity);
   if(status.status!=='disconnected'||attempt===8)return status;
   await new Promise(resolve=>setTimeout(resolve,500));
  }
 }
 async inspect(account,{authorize}={}){
  const id=accountKey(account),ready=await this.ensureReadSession(account,authorize);
  if(ready.status!=='ok')return {...this.status(id),reason:ready.reason};
  const result=await this._run(account,'inspect',async({adapter,identity,valid,authorize:check})=>{
   const connection=await this.waitForConnection(adapter,identity,async()=>valid()&&await check()&&valid());
   if(!valid()||!(await check())||!valid())return blocked('inspect','检查期间成员或账号状态已变化');
   return this._set(id,{loginStatus:'authenticated',connectionStatus:connection.status,connectionState:connection.status,readOnlyCheck:account.paused===true,reason:account.paused?'登录已核验，本次仅检查连接，托管保持暂停':'登录与消息连接检查完成'});
  },authorize);
  return result.accountId?result:{...this.status(id),reason:result.reason};
 }
 async drain(account){const queues=account?[this._queue(accountKey(account))]:[...this.queues.values()];await Promise.all(queues.map(q=>q.drain()));}
 async disconnect(account,reason='已停止账号连接'){if(account){const id=accountKey(account);this.pause(id,reason);await this.drain(id);try{if(this.records.get(id)?.identity)await this.vault.save(id,this._session(id),this.reader.export(id));}catch{}await this._session(id).closeAllConnections();return this.status(id);}this.pauseAll(reason);await this.drain();for(const [id,s]of this.sessions){if(id.startsWith('attempt-')||!this.records.get(id)?.identity)continue;try{await this.vault.save(id,s,this.reader.export(id));}catch{}await s.closeAllConnections();}}
 async revoke(account){const id=accountKey(account);if(this.revocations.has(id))return this.revocations.get(id);const task=(async()=>{this.pause(id,'正在清除此账号在本机的登录');await this.drain(id);const s=this._session(id);try{this.vault.remove(id);this.reader.clear(id);await s.closeAllConnections();await s.clearStorageData();await s.clearCache();await s.clearAuthCache();return this._set(id,{identity:null,externalId:null,loginStatus:'revoked',connectionStatus:'revoked',connectionState:'revoked',automationState:'paused',reason:'已清除此账号在本机的登录；其他设备不受影响'});}catch{return this._set(id,{loginStatus:'revocation_failed',connectionStatus:'revocation_failed',connectionState:'revocation_failed',automationState:'paused',reason:'本机登录未能完整清除，请退出后重试'});}})();this.revocations.set(id,task);try{return await task;}finally{this.revocations.delete(id);}}
 pauseAll(reason='托管已停止'){this.pauseGeneration++;for(const a of this.attempts.values())if(!terminal.has(a.state))this._cancel(a,'cancelled',reason);for(const id of new Set([...this.records.keys(),...this.queues.keys()]))if(!id.startsWith('attempt-'))this.pause(id,reason);}
 async mutateProduct({account}){accountKey(account);return blocked('updateProducts','当前会话尚未逐项验证商品修改入口');}async execute({account,operation}){accountKey(account);return blocked(operation,'此操作尚未在本人会话中逐项验证');}async aiReply({account}){accountKey(account);return blocked('aiReply','尚未配置模型服务');}
}
function createXianyuConnector(options){return new XianyuConnector(options);}module.exports={XianyuConnector,createXianyuConnector,capabilities,blocked,isAllowedNavigation,partitionFor,HOME_URL,LOGIN_URL,BLOCK_REASON};
