'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {EventEmitter}=require('node:events');const {createXianyuConnector,isAllowedNavigation,partitionFor}=require('./xianyu.cjs');const {AccountQueue}=require('./queue.cjs');const {ReadCursorSync}=require('./read-sync.cjs');const normal=require('./normalize.cjs');
// Hypothesis: identity, authorization and network uncertainty remain separated
// under races. Decision: permit the local account manager/queue integration.
// Stop on failure. Fixtures establish local invariants, never platform success.
const tick=()=>new Promise(r=>setImmediate(r));
function fakeElectron(){const sessions=new Map();class BrowserWindow extends EventEmitter{constructor(options){super();this.options=options;this.webContents=new EventEmitter();this.webContents.setWindowOpenHandler=fn=>{this.popup=fn;};this.webContents.getURL=()=>this.url;this.webContents.mainFrame={framesInSubtree:[]};this.destroyed=false;}async loadURL(url){this.url=url;this.webContents.emit('did-finish-load');this.emit('ready-to-show');}show(){}hide(){}focus(){}isDestroyed(){return this.destroyed;}destroy(){this.destroyed=true;this.emit('closed');}}return {BrowserWindow,sessions,session:{fromPartition(key){if(!sessions.has(key)){const s=new EventEmitter();s.setPermissionRequestHandler=fn=>{s.requestPermission=fn;};s.setPermissionCheckHandler=fn=>{s.checkPermission=fn;};s.webRequest={onBeforeRequest:(_f,fn)=>{s.filter=fn;}};for(const a of ['closeAllConnections','clearStorageData','clearCache','clearAuthCache'])s[a]=async()=>{s[a+'Called']=true;};sessions.set(key,s);}return sessions.get(key);}}};}
function fixtureAdapter(own='owner-1'){return {request:async kind=>kind==='identity'?{status:'ok',data:{userId:own,mainUserId:own}}:kind==='profile'?{status:'ok',data:{module:{base:{displayName:'本地协议测试身份'}}}}:{status:'ok',data:{}},connection:async()=>({status:'connected',sendSupported:true}),sessions:async()=>({status:'ok',data:{sessions:[{sessionId:'s1',ownerInfo:{userId:own},userInfo:{userId:'buyer-1'}}],hasMore:false}}),messages:async()=>({status:'ok',data:{messages:[],hasMore:false}}),prepareRecipient:async input=>({status:'ok',...input,verifiedAt:Date.now()}),send:async input=>({status:'accepted',receiptId:'server-id',uuid:input.key})};}
async function ready({own='owner-1',accountId,expectedIdentity,adapter=fixtureAdapter(own)}={}){const electron=fakeElectron(),connector=createXianyuConnector({electron,adapterFactory:()=>adapter,pollMs:60000});const attempt=await connector.startLogin({memberId:'member',accountId,expectedIdentity});const a=connector.attempts.get(attempt.attemptId);await tick();a.window.url='https://www.goofish.com/im';await connector._observe(a);return {electron,connector,a,adapter};}
test('official HTTPS document boundary and five isolated in-memory partitions',()=>{assert.equal(isAllowedNavigation('https://www.goofish.com/'),true);for(const x of ['http://www.goofish.com','https://www.goofish.com.evil.test','https://u:p@www.goofish.com','https://www.goofish.com:444','file:///x'])assert.equal(isAllowedNavigation(x),false);assert.equal(new Set(Array.from({length:5},(_,i)=>partitionFor('a'+i))).size,5);assert.equal(partitionFor('a').startsWith('persist:'),false);});
test('loading official login alone provides no identity or capability and browser has no IPC preload',async()=>{const electron=fakeElectron(),c=createXianyuConnector({electron,pollMs:60000});const a=await c.startLogin({memberId:'m'});const w=c.attempts.get(a.attemptId).window;assert.equal(a.state,'waiting_scan');assert.equal(a.identity,null);assert.equal(a.qrVisible,false);assert.equal(w.options.webPreferences.preload,undefined);assert.equal(w.options.webPreferences.nodeIntegration,false);assert.equal(w.options.webPreferences.sandbox,true);assert.deepEqual(w.popup(),{action:'deny'});assert.throws(()=>c.getLogin({attemptId:a.attemptId,memberId:'wrong'}));c.pauseAll();});
test('trusted identity binds while paused, and duplicate identity can adopt existing local account id',async()=>{const {connector:c,a}=await ready();assert.equal(c.getLogin({attemptId:a.attemptId,memberId:'member'}).state,'success');const bound=await c.bindLogin({attemptId:a.attemptId,memberId:'member',accountId:'preserved-local-id'});assert.equal(bound.externalId,'owner-1');assert.equal(c.status('preserved-local-id').automationState,'paused');assert.equal(c.sessions.has(a.key),false);assert.equal(c.sessions.has('preserved-local-id'),true);assert.ok(bound.sessionGeneration>0);assert.ok(bound.evidenceId);c.pauseAll();});
test('wrong identity re-login rejects before binding and does not overwrite existing account',async()=>{const {connector:c,a}=await ready({accountId:'target',expectedIdentity:'different-owner'});assert.equal(a.state,'failed');assert.equal(a.identity,undefined);await assert.rejects(c.bindLogin({attemptId:a.attemptId,memberId:'member',accountId:'target'}));c.pauseAll();});
test('cancel after identity request starts prevents late successful identity adoption',async()=>{let release;const adapter=fixtureAdapter();adapter.request=kind=>kind==='identity'?new Promise(r=>{release=r;}):Promise.resolve({status:'ok',data:{module:{base:{displayName:'fixture'}}}});const electron=fakeElectron(),c=createXianyuConnector({electron,adapterFactory:()=>adapter,pollMs:60000});const a0=await c.startLogin({memberId:'m'}),a=c.attempts.get(a0.attemptId);await tick();a.window.url='https://www.goofish.com/im';const pending=c._observe(a);c.cancelLogin({attemptId:a.attemptId,memberId:'m'});release({status:'ok',data:{userId:'x'}});await pending;assert.equal(a.state,'cancelled');assert.equal(a.identity,undefined);});
test('expired attempt closes official page and cannot bind',async()=>{const electron=fakeElectron(),c=createXianyuConnector({electron,pollMs:60000});const a0=await c.startLogin({memberId:'m'}),a=c.attempts.get(a0.attemptId);await tick();a.expiresAt=new Date(0).toISOString();await c._observe(a);assert.equal(a.state,'expired');assert.equal(a.window.isDestroyed(),true);});
test('five queues run in parallel while each preserves order and enforces total capacity',async()=>{const qs=Array.from({length:5},()=>new AccountQueue({capacity:2})),started=[],releases=[],order=[];const first=qs.map((q,i)=>q.run(async()=>{started.push(i);await new Promise(r=>{releases[i]=r;});order.push(i+'a');return {status:'ok'};}));await tick();assert.equal(started.length,5);const second=qs.map((q,i)=>q.run(async()=>{order.push(i+'b');return {status:'ok'};}));assert.equal((await qs[0].run(async()=>({status:'ok'}))).status,'rate_limited');releases.forEach(r=>r());await Promise.all([...first,...second]);for(let i=0;i<5;i++)assert.ok(order.indexOf(i+'a')<order.indexOf(i+'b'));});
test('pause during asynchronous authorization prevents submission after permission resolves',async()=>{let release,called=false;const q=new AccountQueue();const task=q.run(async()=>{called=true;return {status:'sent'};},{authorize:()=>new Promise(r=>{release=r;})});await tick();q.pause();release(true);assert.equal((await task).status,'blocked');assert.equal(called,false);});
test('pause cancels waiting work but keeps submitted page alive until drain and records acceptance',async()=>{const {connector:c,a,adapter}=await ready();await c.bindLogin({attemptId:a.attemptId,memberId:'member',accountId:'account'});let release;adapter.send=()=>new Promise(r=>{release=r;});const sending=c.sendMessage({account:'account',buyerId:'buyer-1',text:'fixture',idempotencyKey:'k'});while(!release)await tick();const w=c.windows.get('account');c.pause('account');assert.equal(w.isDestroyed(),false);release({status:'accepted',receiptId:'server-id',uuid:'k'});assert.equal((await sending).status,'accepted');await c.drain('account');await tick();assert.equal(w.isDestroyed(),true);});
test('SDK acceptance alone is not sent; server history match is required and repeated key never submits again',async()=>{const {connector:c,a,adapter}=await ready();await c.bindLogin({attemptId:a.attemptId,memberId:'member',accountId:'account'});let count=0;adapter.send=async input=>{count++;return {status:'accepted',receiptId:'server-id',uuid:input.key};};const request={account:'account',buyerId:'buyer-1',text:'fixture',idempotencyKey:'k'};assert.equal((await c.sendMessage(request)).status,'accepted');assert.equal((await c.sendMessage(request)).status,'accepted');assert.equal(count,1);adapter.messages=async()=>({status:'ok',data:{messages:[{messageId:'server-id',senderInfo:{userId:'owner-1'},content:{text:{text:'fixture'}},timeStamp:Date.now()}]}});assert.equal((await c.sendMessage({...request,idempotencyKey:'k2'})).status,'sent');c.pauseAll();});
test('network interruption after submission stays unknown and cannot automatically retry',async()=>{const {connector:c,a,adapter}=await ready();await c.bindLogin({attemptId:a.attemptId,memberId:'member',accountId:'account'});adapter.send=async()=>{throw Error('network');};const request={account:'account',buyerId:'buyer-1',text:'fixture',idempotencyKey:'k'};assert.equal((await c.sendMessage(request)).status,'unknown');assert.equal((await c.sendMessage(request)).status,'unknown');c.pauseAll();});
test('one account revoke clears only its own storage and failed cleanup is explicit',async()=>{const electron=fakeElectron(),c=createXianyuConnector({electron});c._session('a');c._session('b');assert.equal((await c.revoke('a')).loginStatus,'revoked');assert.equal(electron.sessions.get(partitionFor('b')).clearStorageDataCalled,undefined);c._session('b').clearStorageData=async()=>{throw Error('fixture');};assert.equal((await c.revoke('b')).loginStatus,'revocation_failed');});
test('live identity mismatch invalidates capabilities without touching other accounts',async()=>{const {connector:c,a,adapter}=await ready();await c.bindLogin({attemptId:a.attemptId,memberId:'member',accountId:'a'});c._set('b',{loginStatus:'connected'});adapter.request=async()=>({status:'ok',data:{userId:'somebody-else'}});assert.equal((await c.sync('a','products')).status,'blocked');assert.equal(c.status('a').loginStatus,'identity_mismatch');assert.equal(c.status('b').loginStatus,'connected');c.pauseAll();});
test('product stock and publication are never invented; unproven order detail is refused',()=>{const p=normal.product({cardData:{id:'p',title:'fixture',priceInfo:'12.50'}});assert.equal(p.priceCents,1250);assert.equal(p.stock,undefined);assert.equal(p.status,undefined);assert.throws(()=>normal.order({components:[{render:'orderInfoVO',data:{priceInfo:{amount:'12.50'}}}]},'o','owner',new Date().toISOString(),'e'));assert.throws(()=>normal.identifier(99999999999999999));});
test('product continuation uses official next-page values; failure preserves cursor and newest page remains first',async()=>{const reader=new ReadCursorSync(),calls=[];let fail=false;const adapter={request:async(_k,data)=>{calls.push(data.pageNumber);if(data.pageNumber===2&&fail)return {status:'unavailable'};return {status:'ok',data:{cardList:[{cardData:{id:'p'+data.pageNumber,title:'fixture',priceInfo:'1'}}],nextPage:data.pageNumber===1,nextPageModel:'opaque',nextPageNum:2}};}};const args={id:'a',identity:'own',adapter,kind:'products',valid:()=>true};assert.equal((await reader.run(args)).status,'ok');fail=true;assert.equal((await reader.run(args)).status,'unavailable');assert.equal(reader.export('a').products.pageNumber,2);fail=false;assert.equal((await reader.run(args)).records.length,2);assert.deepEqual(calls,[1,1,2,1,2]);});
test('pause during final async send authorization prevents SDK submission',async()=>{const {connector:c,a,adapter}=await ready();await c.bindLogin({attemptId:a.attemptId,memberId:'member',accountId:'account'});let checks=0,release,submitted=0;adapter.send=async()=>{submitted++;return {status:'unknown'};};const result=c.sendMessage({account:'account',buyerId:'buyer-1',text:'fixture',idempotencyKey:'k',authorize:async()=>{checks++;if(checks===1)return true;return new Promise(r=>{release=r;});}});while(!release)await tick();c.pause('account');release(true);assert.equal((await result).status,'blocked');assert.equal(submitted,0);});
test('failed message history page does not move continuation; new page is read before history',async()=>{const reader=new ReadCursorSync(),adapter=fixtureAdapter('own'),calls=[];let failure=false;adapter.messages=async(_id,_cid,cursor)=>{calls.push(cursor??'latest');if(cursor==='history-2'&&failure)return {status:'unavailable'};return {status:'ok',data:{messages:[],hasMore:cursor==null,nextCursor:cursor==null?'history-2':null}};};const args={id:'a',identity:'own',adapter,kind:'messages',valid:()=>true};assert.equal((await reader.run(args)).status,'ok');failure=true;assert.equal((await reader.run(args)).status,'unavailable');assert.equal(reader.export('a').messages.s1,'history-2');assert.deepEqual(calls,['latest','latest','history-2']);});
test('quick pause then resume drains the submitted send before replacing its page; old close cannot destroy the new page',async()=>{
  const {connector:c,a,adapter}=await ready();
  const bound=await c.bindLogin({attemptId:a.attemptId,memberId:'member',accountId:'account'});
  let release;adapter.send=()=>new Promise(r=>{release=r;});
  const sending=c.sendMessage({account:'account',buyerId:'buyer-1',text:'fixture',idempotencyKey:'lifecycle-send'});
  while(!release)await tick();
  const oldWindow=c.windows.get('account');c.pause('account');
  const resuming=c.resume({id:'account',externalId:'owner-1',sessionVersion:bound.sessionVersion});
  await tick();assert.equal(oldWindow.isDestroyed(),false);assert.equal(c.windows.get('account'),oldWindow);
  release({status:'accepted',receiptId:'server-id',uuid:'lifecycle-send'});
  assert.equal((await sending).status,'accepted');
  const status=await resuming;await tick();
  assert.equal(oldWindow.isDestroyed(),true);assert.notEqual(c.windows.get('account'),oldWindow);
  assert.equal(c.windows.get('account').isDestroyed(),false);assert.equal(status.connectionStatus,'connected');
  c.pauseAll();
});
test('a pause from the starting status callback prevents creating a hidden page',async()=>{
  const {connector:c,a}=await ready();const bound=await c.bindLogin({attemptId:a.attemptId,memberId:'member',accountId:'account'});c.pause('account');
  c.onStatus=status=>{if(status.accountId==='account'&&status.automationState==='starting')c.pause('account','fixture authorization revoked');};
  const result=await c.resume({id:'account',externalId:'owner-1',sessionVersion:bound.sessionVersion});
  assert.equal(c.windows.has('account'),false);assert.equal(result.automationState,'paused');assert.equal(c._queue('account').closed,true);
});
test('actual AccountRuntime hosting and status callbacks recover a previous verification state using unavailable checking capabilities',async()=>{
  const {AccountRuntime}=require('../core/account-runtime.cjs');
  const {connector:c,a}=await ready();const bound=await c.bindLogin({attemptId:a.attemptId,memberId:'member',accountId:'account'});
  const tables=new Map(),table=kind=>{if(!tables.has(kind))tables.set(kind,new Map());return tables.get(kind);};
  const store={list:kind=>[...table(kind).values()],get:(kind,id)=>table(kind).get(id),put:(kind,r)=>{table(kind).set(r.id,structuredClone(r));return r;},transaction:fn=>fn()};
  const actor={id:'member',role:'owner',accountIds:[]};
  store.put('members',{...actor,enabled:true});
  store.put('accounts',{id:'account',accountId:'account',space:'live',externalId:'owner-1',platformUserId:'owner-1',sessionVersion:bound.sessionVersion,paused:true});
  // This connection-state fixture represents an already licensed workspace;
  // expiry and denied-license paths are covered by the licensing integration tests.
  const service={assertLicense:()=>true,_actor:input=>input,_record:(kind,id)=>store.get(kind,id),_audit:()=>{},_public:(_kind,record)=>record};
  const runtime=new AccountRuntime({store,service,connector:c});
  c._set('account',{loginStatus:'verification_required',connectionStatus:'verification_required'});
  const observations=[];c.onStatus=status=>{observations.push(status);runtime.observeStatus(status);};
  runtime.hosting({accountId:'account',enabled:true},actor);
  await Promise.all([...runtime.connectionTasks]);
  const checking=observations.find(s=>s.loginStatus==='checking');assert.ok(checking);
  assert.ok(Object.values(checking.capabilities).every(cap=>cap.available===false));
  assert.equal(store.get('_hosting','account').enabled,true);assert.equal(store.get('accounts','account').connectionStatus,'connected');
  assert.equal(c.windows.get('account').isDestroyed(),false);
  runtime.hosting({accountId:'account',enabled:false},actor);await c.drain('account');
  assert.equal(c.windows.has('account'),false);assert.equal(store.get('_hosting','account').enabled,false);
});
