/* Independent support UI, uses the application's existing theme tokens. */
(()=>{'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const labels={draft:'草稿',queued:'保留在本机，等待回传',received:'云端已收到',attachments_pending:'文字已收到，截图未完成',pending:'等待同步至开发者',delivered:'已进入开发者问题清单',uncertain:'同步结果待核对',blocked:'开发者连接需要处理',forwarding:'正在转交'};
 const button=document.createElement('button');button.id='support-launch';button.textContent='反馈与诊断';button.type='button';button.setAttribute('aria-label','向开发者反馈问题或查看诊断');document.body.append(button);
 const dlg=document.createElement('dialog');dlg.id='support-dialog';dlg.setAttribute('aria-labelledby','support-title');document.body.append(dlg);
 let epoch=0,busy=false,images=[],draftId=null,dirty=false,lastFocus,canvasImage=null;
 async function call(action,p={}){const generation=epoch,r=await window.desk.call('feedback.'+action,p);if(generation!==epoch)throw Error('成员已改变，请重新打开反馈。');if(!r?.ok)throw Error(r?.error?.message||'反馈暂未完成，请保留本机记录。');return r.data;}
 const $=s=>dlg.querySelector(s);
 function header(title){dlg.innerHTML=`<header class="support-head"><h2 id="support-title">${esc(title)}</h2><button type="button" data-support="close" aria-label="关闭反馈">×</button></header><p id="support-error" role="alert"></p><div id="support-body"></div>`;}
 function statusName(r){return labels[r.state]||r.state;}
 function form(report={}){draftId=report.id||null;header('向开发者反馈');$('#support-body').innerHTML=`<p>没有报错但结果不符合预期，也可以在这里说明。自动附带功能与操作状态，不会附带聊天正文或资料内容。</p><form id="support-form"><label>发生问题的功能<select name="feature">${[['account.sync','账号登录与同步'],['order.refresh','订单查看与刷新'],['delivery.execute','资料交付'],['inventory.import','资料与库存'],['message.send','消息与客服'],['license.activate','软件激活'],['app.update','安装与更新'],['renderer.display','界面显示'],['feedback.manual','其他问题']].map(([id,label])=>`<option value="${id}" ${id===(report.feature||'feedback.manual')?'selected':''}>${label}</option>`).join('')}</select></label><label>问题描述<textarea name="description" maxlength="2000" required>${esc(report.description||'')}</textarea></label><label>怎样重现<textarea name="reproduce" maxlength="2000">${esc(report.reproduce||'')}</textarea></label><div class="support-pair"><label>希望出现的结果<textarea name="expected" maxlength="1000">${esc(report.expected||'')}</textarea></label><label>实际出现的结果<textarea name="actual" maxlength="1000">${esc(report.actual||'')}</textarea></label></div><label>联系方式（可选）<input name="contact" maxlength="200" value="${esc(report.contact||'')}"></label><section><h3>截图（可选）</h3><p>最多两张。先遮挡买家信息、资料链接和密钥，再确认发送。</p><div id="support-images"></div><button type="button" data-support="choose">选择截图</button><div id="support-editor"></div></section><div class="support-actions"><button type="button" data-support="save">保存草稿</button><button type="button" data-support="preview">预览诊断</button><button class="primary" type="submit">确认提交反馈</button></div><pre id="support-preview" hidden></pre></form>`;renderImages();dirty=false;}
 function payload(){const values=Object.fromEntries(new FormData($('#support-form')));return {...values,...(draftId?{id:draftId}:{}),attachmentIds:images.map(x=>x.meta.id)};}
 function renderImages(){const node=$('#support-images');if(node)node.innerHTML=images.map((x,i)=>`<figure><img alt="待发送截图 ${i+1}" src="${esc(x.url)}"><figcaption>截图 ${i+1} <button type="button" data-support="remove" data-index="${i}">移除</button></figcaption></figure>`).join('');}
 async function history(){header('反馈与诊断');const [info,list]=await Promise.all([call('status'),call('list')]);$('#support-body').innerHTML=`<p>${esc(info.privacy)}</p><p role="status">回传连接：${info.connection==='connected'?'已取得收件回执':'尚未接通或暂不可用'}${info.code?'（'+esc(info.code)+'）':''}</p>${info.noticeRequired?'<p class="support-notice">软件已激活，脱敏错误自动回传已默认开启。可在下方关闭；主动反馈仍可使用。</p>':''}<div class="support-actions"><button class="primary" data-support="new">向开发者反馈</button><button data-support="export">导出脱敏诊断</button>${info.canConfigure?`<label class="support-switch"><input id="support-auto" type="checkbox" ${info.automatic?'checked':''}>自动回传脱敏错误</label><button data-support="settings">保存设置</button><button data-support="clear">清理已完整收件的本机记录</button>`:''}</div><h3>我的反馈</h3>${list.length?`<div class="table-wrap"><table><thead><tr><th>时间 / 功能</th><th>收件状态</th><th>操作</th></tr></thead><tbody>${list.map(r=>`<tr><td>${esc(new Date(r.at).toLocaleString())}<br>${esc(r.feature)}</td><td>${esc(statusName(r))}<br>${esc(labels[r.github]||'')}${r.code?'<br>'+esc(r.code):''}</td><td><button data-support="detail" data-id="${esc(r.id)}">${r.state==='draft'?'继续草稿':'查看内容'}</button>${r.state!=='draft'?`<button data-support="retry" data-id="${esc(r.id)}">核对 / 继续提交</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:'<p>还没有反馈记录。遇到操作不符合预期时，可以主动提交说明。</p>'}`;dirty=false;}
 async function run(fn){if(busy)return;busy=true;dlg.setAttribute('aria-busy','true');try{await fn();}catch(e){const target=$('#support-error');if(target){target.style.color='var(--danger)';target.textContent=e.message;}}finally{busy=false;dlg.removeAttribute('aria-busy');}}
 async function open(){lastFocus=document.activeElement;if(!dlg.open)dlg.showModal();await run(history);}
 function close(){if(busy)return;if(dirty&&!confirm('反馈尚未保存，确定关闭吗？'))return;dlg.close();lastFocus?.focus();dirty=false;}
 button.onclick=open;dlg.addEventListener('cancel',e=>{e.preventDefault();close();});
 dlg.addEventListener('input',()=>{dirty=true;});
 dlg.addEventListener('click',e=>{const b=e.target.closest('[data-support]');if(!b)return;const action=b.dataset.support;if(action==='close')return close();run(async()=>{
  if(action==='new'){images=[];form();}
  if(action==='settings'){await call('settings',{automatic:$('#support-auto').checked,noticed:true});await history();}
  if(action==='clear'){if(confirm('仅移除本机已完整收件的反馈，云端记录保留。是否继续？')){await call('clear');await history();}}
  if(action==='export')await call('export');
  if(action==='save'){const saved=await call('draft',payload());draftId=saved.id;dirty=false;$('#support-error').textContent='草稿已加密保存在本机。';}
  if(action==='preview'){const r=await call('preview',payload());draftId=r.id;const view=$('#support-preview');view.hidden=false;view.textContent=JSON.stringify(r,null,2);}
  if(action==='remove'){images.splice(Number(b.dataset.index),1);renderImages();dirty=true;}
  if(action==='detail'){const report=await call('detail',{id:b.dataset.id});const rows=await call('list');if(rows.find(r=>r.id===b.dataset.id)?.state==='draft'){images=[];for(const a of report.attachments){const image=await call('image.read',{id:report.id,attachmentId:a.id});images.push({meta:a,url:image.dataUrl});}form(report);}else{header('反馈内容');$('#support-body').innerHTML=`<pre>${esc(JSON.stringify(report,null,2))}</pre><button data-support="back">返回记录</button>`;}}
  if(action==='back')await history();
  if(action==='retry'){const row=(await call('list')).find(x=>x.id===b.dataset.id);if(['queued','attachments_pending'].includes(row.state))await call('submit',{id:row.id});else await call('refresh',{id:row.id});await history();}
  if(action==='choose'){if(images.length>=2)throw Error('最多添加两张截图。');const image=await call('image.choose');if(image.canceled)return;const section=$('#support-editor');section.innerHTML='<p>拖动框选区域可遮挡；也可填写下方坐标，用键盘完成遮挡。</p><canvas id="support-canvas" aria-label="截图预览"></canvas><div class="support-mask-fields">'+['x','y','width','height'].map((n,i)=>`<label>${['左侧','顶部','宽度','高度'][i]}<input type="number" min="0" name="mask-${n}" value="0"></label>`).join('')+'</div><button type="button" data-support="mask">遮挡所填区域</button><button type="button" data-support="accept-image">确认这张截图</button>';canvasImage=new Image();await new Promise((resolve,reject)=>{canvasImage.onload=resolve;canvasImage.onerror=reject;canvasImage.src=image.dataUrl;});const c=$('#support-canvas');c.width=canvasImage.width;c.height=canvasImage.height;c.getContext('2d').drawImage(canvasImage,0,0);let start;const point=e=>{const r=c.getBoundingClientRect();return {x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height};};c.onpointerdown=e=>{start=point(e);c.setPointerCapture(e.pointerId);};c.onpointerup=e=>{if(!start)return;const p=point(e),ctx=c.getContext('2d');ctx.fillStyle='#171717';ctx.fillRect(Math.min(start.x,p.x),Math.min(start.y,p.y),Math.abs(start.x-p.x),Math.abs(start.y-p.y));start=null;};}
  if(action==='mask'){const c=$('#support-canvas'),ctx=c.getContext('2d');ctx.fillStyle='#171717';ctx.fillRect(...['x','y','width','height'].map(n=>Number($(`[name="mask-${n}"]`).value)||0));}
  if(action==='accept-image'){const url=$('#support-canvas').toDataURL('image/jpeg',.8),meta=await call('image.store',{dataUrl:url});images.push({meta,url});$('#support-editor').innerHTML='';renderImages();dirty=true;}
 });});
 dlg.addEventListener('submit',e=>{if(e.target.id!=='support-form')return;e.preventDefault();if(!e.target.reportValidity())return;run(async()=>{await call('submit',payload());dirty=false;await history();});});
 window.LianpuFeedback={open};
 window.addEventListener('error',e=>{void call('clientError',{feature:'uncaught',code:'RENDERER_ERROR',stack:e.error?.stack||''}).catch(()=>{});});
 window.addEventListener('unhandledrejection',e=>{void call('clientError',{feature:'rejection',code:'RENDERER_REJECTION',stack:e.reason?.stack||''}).catch(()=>{});});
 window.desk?.onEvent(event=>{if(['member-changed','access-revoked','workspace-closed'].includes(event.type)){epoch++;images=[];dirty=false;dlg.close();}if(event.type==='license-changed')void call('status').then(info=>{button.textContent=info.noticeRequired?'自动诊断已开启 · 查看设置':'反馈与诊断';}).catch(()=>{});});
 void call('status').then(info=>{if(info.noticeRequired)button.textContent='自动诊断已开启 · 查看设置';}).catch(()=>{});
})();
