/* Lianpu business views. Independently implemented against the existing desktop bridge.
 * General layout references: Shadcn Admin e16c87f213a5ba5e45964e9b67c792105ec74d26.
 * No upstream dashboard metrics, contacts, authentication or business data are used. */
(() => {
  'use strict';
  function overview(c) {
    const {state,rows,get,e,t,when,badge,btn,heading,empty,notice,accountName,assetName}=c;
    const uncertain=rows('deliveries').filter(d=>['unknown','accepted','sending'].includes(d.status));
    const service=rows('serviceJobs').filter(j=>['pending','waiting','failed','unknown'].includes(j.status));
    const afterSales=rows('afterSales').filter(a=>!['closed','completed','resolved'].includes(a.status));
    const low=rows('assets').filter(a=>a.type==='unique'&&rows('inventory').filter(i=>i.assetId===a.id&&i.status==='available').length<=Number(a.threshold||0));
    const attention=rows('accounts').filter(a=>!a.archived&&(a.space==='test'?a.paused||a.status!=='test_ready':a.paused||a.loginStatus!=='authenticated'||a.connectionStatus!=='connected'||a.hosting?.enabled!==true));
    const pending=rows('orders').filter(o=>o.paymentStatus==='paid'&&!rows('deliveries').some(d=>d.orderId===o.id&&!d.serviceId&&['sent','delivered','verified_sent'].includes(d.status)));
    const stats=[['交付待核验',uncertain.length,'orders','先核对原尝试'],['已付款待处理',pending.length,'orders','依订单事实判断'],['库存需补充',low.length,'inventory','按资料阈值检查'],['售后未结束',afterSales.length,'afterSales','保留期限与依据']];
    const task=(title,description,action,attrs,tone='')=>`<article class="work-item"><div class="work-item-main"><strong>${e(title)}</strong><span>${e(description)}</span></div><div class="work-item-meta">${tone?badge(tone):''}${btn('查看',''+action,attrs,'small')}</div></article>`;
    const orderTasks=uncertain.slice(0,5).map(d=>{const o=get('orders',d.orderId);return task(o?.externalId||d.orderId||'交付记录',`${accountName(d.accountId)} · ${d.reason||'先核验原发送结果，避免重复交付。'}`,'related-order',`data-id="${e(d.orderId)}"`,d.status);}).join('');
    const otherTasks=afterSales.slice(0,3).map(a=>task(a.reason||'售后记录',`${a.dueAt?'处理期限 '+when(a.dueAt):'未设置期限'} · ${accountName(a.accountId)}`,'related-editor',`data-kind="afterSales" data-id="${e(a.id)}"`,a.status)).join('');
    const upcoming=service.slice(0,3).map(j=>task(get('orders',j.orderId)?.externalId||'订单后续服务',j.reason||'按可信事件与已保存规则处理。','navigate','data-route="afterSales"',j.status)).join('');
    return heading('工作台','从需要核验的事实开始，安排今天的经营工作。',btn('经营提醒','notifications')+(state.space==='live'&&state.auth?.user?.role==='owner'?btn('添加闲鱼账号','account-add','','primary'):btn('查看订单','navigate','data-route="orders"','primary')))+
      `<section class="overview-summary" aria-label="当前范围的本机待办数量">${stats.map(([label,count,route,help])=>`<button class="overview-stat" data-action="navigate" data-route="${route}"><span>${label}</span><strong class="number">${count}</strong><small>${help}</small></button>`).join('')}</section>`+
      `<div class="overview-grid"><section><div class="section-head"><div><h2>优先处理</h2><p>仅依据当前账号范围内已有的本机记录。</p></div><span class="muted">更新于 ${e(when(state.lastSync))}</span></div><div class="work-list">${orderTasks+otherTasks+upcoming||empty('当前没有待核验事项',rows('accounts').length?'可以继续整理商品、检查资料和规则。没有同步到本机的事项不会出现在这里。':'先添加自己的经营账号、整理资料，并查看当前可用的连接能力。',(state.space==='live'&&state.auth?.user?.role==='owner'?btn('添加闲鱼账号','account-add','','primary'):btn('经营账号','navigate','data-route="accounts"')))}</div><section class="block"><div class="section-head"><h2>继续整理</h2></div><div class="linked-records">${btn('商品与规格绑定','navigate','data-route="products"')}${btn('资料与版本','navigate','data-route="assets"')}${btn('买家会话','navigate','data-route="messages"')}${btn('交付规则试运行','navigate','data-route="rules"')}</div></section></section><aside><section class="block"><div class="section-head"><h2>账号状态</h2>${btn('管理','navigate','data-route="accounts"','small quiet')}</div>${rows('accounts').length?rows('accounts').map(a=>`<article class="work-item"><div class="work-item-main"><strong>${e(a.name)}</strong><small>登录：${e(window.LianpuAccountViews.status(a).login)}</small><small>消息：${e(window.LianpuAccountViews.status(a).connection)} · 托管：${e(window.LianpuAccountViews.status(a).hosting)}</small></div>${btn('详情','account-detail',`data-id="${e(a.id)}"`,'small quiet')}</article>`).join(''):notice('尚未添加经营账号。真实经营工作区保持为空。')}${attention.length?`<p class="help">${attention.length} 个账号需要留意。打开网页登录不等于获得自动经营能力。</p>`:''}</section><section class="block"><div class="section-head"><h2>库存提醒</h2>${btn('盘点','navigate','data-route="inventory"','small quiet')}</div>${low.length?low.map(a=>`<article class="work-item"><div class="work-item-main"><strong>${e(assetName(a.id))}</strong><small>可用 ${rows('inventory').filter(i=>i.assetId===a.id&&i.status==='available').length} 条 · 阈值 ${e(a.threshold||0)}</small></div>${btn('补充','inventory-import',`data-id="${e(a.id)}"`,'small')}</article>`).join(''):'<p class="help">当前范围没有达到低库存阈值的唯一资料。</p>'}</section><p class="help">${state.space==='test'?'此页为隔离测试数据，不计入真实经营。':'这里展示本机已取得的数据，不代表平台上的完整经营情况。'}</p></aside></div>`;
  }
  function products(c) {
    const {state,rows,e,money,badge,btn,heading,searchBar,table,empty,source,accountName,searched}=c;
    const records=searched(rows('products')).filter(p=>state.filter==='all'||(p.status||'draft')===state.filter);
    const filters=`<select data-filter aria-label="商品状态"><option value="all" ${state.filter==='all'?'selected':''}>全部状态</option>${['draft','active','inactive'].map(s=>`<option value="${s}" ${state.filter===s?'selected':''}>${{draft:'草稿',active:'上架',inactive:'下架'}[s]}</option>`).join('')}</select>${btn('导入商品','choose-import','data-kind="products"')}`;
    return heading('商品管理','维护本机商品、规格和资料绑定，平台状态单独核对。',btn('素材库','media-open')+btn('同步商品','sync','data-kind="products"')+btn('新建商品','edit','data-kind="products"','primary'))+searchBar('搜索标题、编码或分类',filters)+
      `<div class="selection-bar" aria-live="polite"><span data-selection-summary>${state.checked.size} 个商品已选择</span>${btn(`批量变更${state.checked.size?`（${state.checked.size}）`:''}`,'batch-edit','data-batch-button','small')}<small>选择仅限当前页；翻页或筛选时清除。</small></div>`+
      (records.length?table(['<input type="checkbox" data-check-all aria-label="选择当前显示商品">','商品 / 商家编码','售价','库存','规格 / 账号','档案状态','操作'],records.map(p=>`<tr data-record-id="${e(p.id)}"><td><input type="checkbox" data-product-check="${e(p.id)}" ${state.checked.has(p.id)?'checked':''} aria-label="选择 ${e(p.title)}"></td><td class="primary-cell">${btn(p.title,'related-product',`data-id="${e(p.id)}"`,'link entity-title')}<small>${e(p.sku||'未填商家编码')} · ${e(p.category||'未分类')}</small>${source(p)}</td><td class="number" data-sort-value="${Number(p.priceCents)||0}">${money(p.priceCents)}</td><td data-sort-value="${Number(p.stock)||0}">${e(p.stock??'未设置')}</td><td>${p.variants?.length||0} 个规格<small>${e(accountName(p.accountId))}</small></td><td>${badge(p.status||'draft')}</td><td class="row-actions">${btn('编辑','edit',`data-kind="products" data-id="${e(p.id)}"`,'small')}${btn('复制档案','clone-product',`data-id="${e(p.id)}"`,'small quiet')}${btn('复制到账号','clone-account',`data-id="${e(p.id)}"`,'small quiet')}</td></tr>`).join('')):empty('建立商品与资料的对应关系','先保存商品档案，再为每个规格绑定完整资料包。真实发布需要平台账号具有对应能力。',btn('新建商品档案','edit','data-kind="products"','primary')));
  }
  function assetTabs(c) {
    const {state,rows,e}=c;
    return `<div class="catalog-tabs" role="tablist" aria-label="资料分类">${[['all','全部资料'],['fixed','固定资料'],['unique','唯一内容'],['bundle','组合资料']].map(([id,label])=>`<button type="button" role="tab" aria-selected="${state.filter===id}" class="catalog-tab" data-action="set-filter" data-filter-value="${id}">${label}<span>${id==='all'?rows('assets').length:rows('assets').filter(a=>a.type===id).length}</span></button>`).join('')}</div>`;
  }
  function assets(c) {
    const {state,rows,e,badge,btn,heading,searchBar,table,empty,notice,searched}=c;
    const records=searched(rows('assets')).filter(a=>state.filter==='all'||a.type===state.filter);
    return heading('资料库','完整保存链接、提取码与说明，按资料类型安排交付。',btn('唯一库存','navigate','data-route="inventory"')+btn('素材库','media-open')+btn('新建资料','edit','data-kind="assets"','primary'))+assetTabs(c)+searchBar('搜索资料名称、版本或分类')+
      (records.length?table(['资料 / 版本','类型','关联商品 / 库存','操作'],records.map(a=>`<tr data-record-id="${e(a.id)}"><td class="primary-cell">${btn(a.name,'related-asset',`data-id="${e(a.id)}"`,'link entity-title')}<small>${e(a.category||'未分类')} · 版本 ${e(a.version||1)}</small><small>${e(a.type==='unique'?'逐条分配，每份仅交付一次':a.type==='bundle'?`${a.items?.length||0} 个组合条目`:a.link||'尚未填写资料链接')}</small></td><td>${badge(a.type||'fixed')}</td><td>${rows('products').filter(p=>p.accountId===a.accountId&&p.variants?.some(v=>v.assetId===a.id)).length} 个商品${a.type==='unique'?`<small>可用 ${rows('inventory').filter(i=>i.assetId===a.id&&i.status==='available').length} 条 · 阈值 ${e(a.threshold||0)}</small>`:''}</td><td class="row-actions">${btn('查看 / 编辑','edit',`data-kind="assets" data-id="${e(a.id)}"`,'small')}${btn('内容预览','asset-preview',`data-id="${e(a.id)}"`,'small quiet')}${a.type==='unique'?btn('补充库存','inventory-import',`data-id="${e(a.id)}"`,'small quiet'):''}</td></tr>`).join('')):empty('把一份资料完整保存','固定资料可重复交付；唯一内容逐条分配；组合资料按保存顺序合并。',btn('建立第一份资料','edit','data-kind="assets"','primary')))+notice('修改仅影响后续交付。已有交付和已承诺的收货后服务保留原版本；保存链接不能证明网盘仍可访问。');
  }
  function productDetail(c,id) {
    const {get,rows,e,t,money,badge,btn,table,empty,accountName,assetName}=c,p=get('products',id);
    if(!p)return empty('商品已不在当前范围','请回到列表重新选择。');
    const orders=rows('orders').filter(o=>o.accountId===p.accountId&&o.productId===id);
    return `<dl class="detail-grid"><dt>所属账号</dt><dd>${e(accountName(p.accountId))}</dd><dt>商家编码</dt><dd class="number">${e(p.sku||'未设置')}</dd><dt>售价 / 库存</dt><dd>${money(p.priceCents)} / ${e(p.stock??'未设置')}</dd><dt>本机档案</dt><dd>${badge(p.status||'draft')}</dd><dt>平台状态</dt><dd>${badge(p.platformStatus||'not_verified')}</dd></dl><section class="form-section"><h3>商品说明</h3><div class="content-preview">${e(p.description||'尚未填写说明。')}</div></section><section class="form-section"><div class="section-head"><h3>规格与资料绑定</h3>${btn('编辑绑定','edit',`data-kind="products" data-id="${e(id)}"`,'small')}</div>${p.variants?.length?table(['规格','售价 / 份数','关联资料'],p.variants.map(v=>{const a=get('assets',v.assetId);return `<tr><td>${e(v.name)}</td><td>${money(v.priceCents)}<small>${e(v.quantity||1)} 份</small></td><td>${a&&a.accountId===p.accountId?btn(assetName(a.id),'related-asset',`data-id="${e(a.id)}"`,'link'):e('尚未绑定可用资料')}</td></tr>`;}).join('')):'<p class="help">尚未建立规格。保存规格与资料绑定后，可到规则中试运行。</p>'}</section><section class="form-section"><h3>关联订单 <span class="muted">${orders.length}</span></h3><div class="linked-records">${orders.map(o=>btn(o.externalId||o.id,'related-order',`data-id="${e(o.id)}"`,'small')).join('')||'<p class="help">当前范围没有关联订单。</p>'}</div></section><div class="form-end">${btn('关闭','close-dialog')}${btn('编辑商品','edit',`data-kind="products" data-id="${e(id)}"`,'primary')}</div>`;
  }
  function assetDetail(c,id) {
    const {get,rows,e,badge,btn,notice,accountName}=c,a=get('assets',id);
    if(!a)return '';
    const products=rows('products').filter(p=>p.accountId===a.accountId&&p.variants?.some(v=>v.assetId===id));
    return `<dl class="detail-grid"><dt>所属账号</dt><dd>${e(accountName(a.accountId))}</dd><dt>类型 / 版本</dt><dd>${badge(a.type||'fixed')} ${e(a.version||1)}</dd><dt>分类</dt><dd>${e(a.category||'未分类')}</dd></dl><section class="form-section"><h3>交付内容</h3>${a.type==='unique'?notice('交付时才预留唯一内容。此详情不会占用或消耗库存。'):a.type==='bundle'?`<div class="linked-records">${(a.items||[]).map(item=>{const child=get('assets',item.assetId);return child&&child.accountId===a.accountId?btn(`${child.name} × ${item.quantity||1}`,'related-asset',`data-id="${e(child.id)}"`,'small'):'<span>关联资料不可用</span>';}).join('')}</div>`:`<div class="content-preview">${e([a.link,a.code?`提取码：${a.code}`:'',a.instructions].filter(Boolean).join('\n')||'当前角色没有可展示的内容，或尚未填写。')}</div>`}</section><section class="form-section"><h3>绑定商品 <span class="muted">${products.length}</span></h3><div class="linked-records">${products.map(p=>btn(p.title,'related-product',`data-id="${e(p.id)}"`,'small')).join('')||'<p class="help">尚无商品规格绑定这份资料。</p>'}</div></section><div class="form-end">${btn('关闭','close-dialog')}${a.type==='unique'?btn('补充库存','inventory-import',`data-id="${e(id)}"`):''}${btn('编辑资料','edit',`data-kind="assets" data-id="${e(id)}"`,'primary')}</div>`;
  }
  function messages(c) {
    const {state,get,rows,e,t,when,badge,btn,heading,empty,searched,accountName,productName}=c;
    const records=searched(rows('conversations'),['buyerId','lastMessage']).sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned));
    const conversation=get('conversations',state.selectedConversation)||records[0];
    const orders=conversation?rows('orders').filter(o=>o.accountId===conversation.accountId&&(o.id===conversation.orderId||o.buyerId===conversation.buyerId)):[];
    const product=conversation?get('products',conversation.productId):null;
    const related=conversation?`<aside class="chat-related"><h3>关联信息</h3><dl class="facts"><dt>经营账号</dt><dd>${e(accountName(conversation.accountId))}</dd><dt>买家编号</dt><dd class="number">${e(conversation.buyerId)}</dd></dl>${product&&product.accountId===conversation.accountId?`<section class="block"><h3>商品</h3>${btn(productName(product.id),'related-product',`data-id="${e(product.id)}"`,'link')}</section>`:''}<section class="block"><h3>同买家订单</h3><div class="linked-records">${orders.map(o=>btn(o.externalId||o.id,'related-order',`data-id="${e(o.id)}"`,'small')).join('')||'<p class="help">当前范围没有关联订单。</p>'}</div></section><p class="help">发送前会再次核对账号、买家和完整内容。</p></aside>`:'';
    const content=conversation?`<section class="chat"><header class="chat-header"><div><h2>${e(conversation.buyerName||conversation.buyerId)}</h2><small>${e(accountName(conversation.accountId))} · 买家 ${e(conversation.buyerId)}</small>${conversation.assigneeId?`<small class="source-text">接待人：${e(get('members',conversation.assigneeId)?.name||(state.auth.user?.id===conversation.assigneeId?state.auth.user.name:'已指定成员'))}</small>`:''}</div><div class="actions">${badge(conversation.manual?'人工接管':'自动回复按规则')}${btn(conversation.manual?'结束接管':'人工接管','takeover',`data-id="${e(conversation.id)}"`,'small')}</div></header><div class="chat-messages" aria-label="当前会话消息">${rows('messages').filter(m=>m.conversationId===conversation.id).map(m=>`<article class="chat-message ${['out','outgoing','seller'].includes(m.direction)?'ours':''}"><small>${e(['out','outgoing','seller'].includes(m.direction)?'店铺':conversation.buyerName||'买家')} · ${e(when(m.createdAt))}</small><div class="bubble">${e(m.text||m.content||'当前角色没有可展示的内容')}</div><small>${e(t(m.status||'已存档'))}</small></article>`).join('')||'<p class="help">尚无同步消息。需要账号具有消息读取能力。</p>'}</div><form id="message-form" class="chat-compose" data-id="${e(conversation.id)}"><label for="reply-text">回复给 ${e(conversation.buyerName||conversation.buyerId)}</label><textarea id="reply-text" name="text" required placeholder="输入答复，下一步核对接收方与完整内容。">${e(state.messageDraft?.id===conversation.id?state.messageDraft.text:'')}</textarea><div class="actions">${btn('常用短语','pick-snippet')}${btn('规则试答','reply-preview',`data-id="${e(conversation.id)}"`)}${btn('AI 试答','ai-preview',`data-id="${e(conversation.id)}"`)}<button type="submit" class="primary">预览回复</button></div></form></section>`:empty('等待第一条买家会话','同步自己账号的消息后，在这里核对买家与订单。',btn('经营账号','navigate','data-route="accounts"'));
    return heading('消息与客服','核对当前账号和买家，再接管、试答或回复。',btn('管理短语','snippets')+btn('同步消息','sync','data-kind="messages"','primary'))+`<div class="conversation-layout ${conversation?'has-related':''}"><aside class="conversations" aria-label="会话列表"><div class="conversation-search"><label class="visually-hidden" for="local-search">搜索买家或会话</label><input id="local-search" type="search" data-search value="${e(state.search)}" placeholder="搜索买家或会话"></div>${records.map(v=>`<button class="conversation-item ${conversation?.id===v.id?'selected':''}" aria-current="${conversation?.id===v.id?'true':'false'}" data-action="select-conversation" data-id="${e(v.id)}"><strong>${e(v.buyerName||v.buyerId)}${v.unread?`<span class="badge good">${e(v.unread)}</span>`:''}</strong><small>${e(v.lastMessage||'查看会话记录')}</small><small>${e(accountName(v.accountId))}${v.pinned?' · 已置顶':''}${v.manual?' · 人工接管':''}</small></button>`).join('')||'<p class="help">没有符合条件的本机会话。</p>'}</aside>${content}${related}</div>`;
  }
  window.LianpuViews=Object.freeze({overview,products,assets,productDetail,assetDetail,messages});
})();
